// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AnalyzePurchaseData, AnalyzePurchaseErrors, AnalyzePurchaseResponses, ConfirmPairingData, ConfirmPairingErrors, ConfirmPairingResponses, CreateAuthSessionData, CreateAuthSessionErrors, CreateAuthSessionResponses, CreateChatMessageData, CreateChatMessageResponses, CreateGoalData, CreateGoalErrors, CreateGoalResponses, CreateImportData, CreateImportResponses, CreatePairingSessionData, CreatePairingSessionResponses, GetAiRuntimeConfigData, GetAiRuntimeConfigErrors, GetAiRuntimeConfigResponses, GetHealthData, GetHealthResponses, GetHouseholdContextData, GetHouseholdContextErrors, GetHouseholdContextResponses, ListAccountsData, ListAccountsErrors, ListAccountsResponses, ListBillsData, ListBillsErrors, ListBillsResponses, ListGoalsData, ListGoalsErrors, ListGoalsResponses, ListImportsData, ListImportsResponses, ListIncomeSourcesData, ListIncomeSourcesErrors, ListIncomeSourcesResponses, ListReportsData, ListReportsResponses, ListTransactionsData, ListTransactionsErrors, ListTransactionsResponses, UpdateAiRuntimeConfigData, UpdateAiRuntimeConfigErrors, UpdateAiRuntimeConfigResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Check API health
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Create a short-lived pairing session for a device
 */
export const createPairingSession = <ThrowOnError extends boolean = false>(options?: Options<CreatePairingSessionData, ThrowOnError>): RequestResult<CreatePairingSessionResponses, unknown, ThrowOnError> => (options?.client ?? client).post<CreatePairingSessionResponses, unknown, ThrowOnError>({ url: '/pairing/sessions', ...options });

/**
 * Confirm mobile device pairing
 */
export const confirmPairing = <ThrowOnError extends boolean = false>(options: Options<ConfirmPairingData, ThrowOnError>): RequestResult<ConfirmPairingResponses, ConfirmPairingErrors, ThrowOnError> => (options.client ?? client).post<ConfirmPairingResponses, ConfirmPairingErrors, ThrowOnError>({
    url: '/pairing/confirm',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create a local authentication session
 */
export const createAuthSession = <ThrowOnError extends boolean = false>(options: Options<CreateAuthSessionData, ThrowOnError>): RequestResult<CreateAuthSessionResponses, CreateAuthSessionErrors, ThrowOnError> => (options.client ?? client).post<CreateAuthSessionResponses, CreateAuthSessionErrors, ThrowOnError>({
    url: '/auth/sessions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get household financial context summary
 */
export const getHouseholdContext = <ThrowOnError extends boolean = false>(options?: Options<GetHouseholdContextData, ThrowOnError>): RequestResult<GetHouseholdContextResponses, GetHouseholdContextErrors, ThrowOnError> => (options?.client ?? client).get<GetHouseholdContextResponses, GetHouseholdContextErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/household',
    ...options
});

/**
 * List accounts
 */
export const listAccounts = <ThrowOnError extends boolean = false>(options?: Options<ListAccountsData, ThrowOnError>): RequestResult<ListAccountsResponses, ListAccountsErrors, ThrowOnError> => (options?.client ?? client).get<ListAccountsResponses, ListAccountsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/accounts',
    ...options
});

/**
 * List transactions for the household
 */
export const listTransactions = <ThrowOnError extends boolean = false>(options?: Options<ListTransactionsData, ThrowOnError>): RequestResult<ListTransactionsResponses, ListTransactionsErrors, ThrowOnError> => (options?.client ?? client).get<ListTransactionsResponses, ListTransactionsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/transactions',
    ...options
});

/**
 * List recurring bills for the household
 */
export const listBills = <ThrowOnError extends boolean = false>(options?: Options<ListBillsData, ThrowOnError>): RequestResult<ListBillsResponses, ListBillsErrors, ThrowOnError> => (options?.client ?? client).get<ListBillsResponses, ListBillsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/bills',
    ...options
});

/**
 * List income sources for the household
 */
export const listIncomeSources = <ThrowOnError extends boolean = false>(options?: Options<ListIncomeSourcesData, ThrowOnError>): RequestResult<ListIncomeSourcesResponses, ListIncomeSourcesErrors, ThrowOnError> => (options?.client ?? client).get<ListIncomeSourcesResponses, ListIncomeSourcesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/income',
    ...options
});

/**
 * List financial goals
 */
export const listGoals = <ThrowOnError extends boolean = false>(options?: Options<ListGoalsData, ThrowOnError>): RequestResult<ListGoalsResponses, ListGoalsErrors, ThrowOnError> => (options?.client ?? client).get<ListGoalsResponses, ListGoalsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/goals',
    ...options
});

/**
 * Create a financial goal
 */
export const createGoal = <ThrowOnError extends boolean = false>(options: Options<CreateGoalData, ThrowOnError>): RequestResult<CreateGoalResponses, CreateGoalErrors, ThrowOnError> => (options.client ?? client).post<CreateGoalResponses, CreateGoalErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/goals',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Analyze the financial impact of a potential purchase
 */
export const analyzePurchase = <ThrowOnError extends boolean = false>(options: Options<AnalyzePurchaseData, ThrowOnError>): RequestResult<AnalyzePurchaseResponses, AnalyzePurchaseErrors, ThrowOnError> => (options.client ?? client).post<AnalyzePurchaseResponses, AnalyzePurchaseErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/advisor/purchase',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Send a message to the financial advisor
 */
export const createChatMessage = <ThrowOnError extends boolean = false>(options: Options<CreateChatMessageData, ThrowOnError>): RequestResult<CreateChatMessageResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateChatMessageResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/chat/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List import jobs
 */
export const listImports = <ThrowOnError extends boolean = false>(options?: Options<ListImportsData, ThrowOnError>): RequestResult<ListImportsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListImportsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/imports',
    ...options
});

/**
 * Register a financial data import
 */
export const createImport = <ThrowOnError extends boolean = false>(options: Options<CreateImportData, ThrowOnError>): RequestResult<CreateImportResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateImportResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/imports',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List generated reports
 */
export const listReports = <ThrowOnError extends boolean = false>(options?: Options<ListReportsData, ThrowOnError>): RequestResult<ListReportsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListReportsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/reports',
    ...options
});

/**
 * Get active AI runtime configuration
 */
export const getAiRuntimeConfig = <ThrowOnError extends boolean = false>(options?: Options<GetAiRuntimeConfigData, ThrowOnError>): RequestResult<GetAiRuntimeConfigResponses, GetAiRuntimeConfigErrors, ThrowOnError> => (options?.client ?? client).get<GetAiRuntimeConfigResponses, GetAiRuntimeConfigErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/ai/runtime',
    ...options
});

/**
 * Update AI runtime configuration
 */
export const updateAiRuntimeConfig = <ThrowOnError extends boolean = false>(options: Options<UpdateAiRuntimeConfigData, ThrowOnError>): RequestResult<UpdateAiRuntimeConfigResponses, UpdateAiRuntimeConfigErrors, ThrowOnError> => (options.client ?? client).put<UpdateAiRuntimeConfigResponses, UpdateAiRuntimeConfigErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/ai/runtime',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
