// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type HealthResponse = {
    status: 'ok' | 'degraded';
    version: string;
};

export type ErrorResponse = {
    error: {
        code: string;
        message: string;
        details?: {
            [key: string]: unknown;
        };
    };
};

export type Money = {
    /**
     * Signed integer amount in minor currency units.
     */
    amount_minor: number;
    currency: string;
};

export type PairingSession = {
    id: string;
    qr_payload: string;
    expires_at: string;
};

export type PairingConfirmRequest = {
    pairing_session_id: string;
    device_name: string;
    device_public_key: string;
};

export type DeviceCredential = {
    device_id: string;
    access_token: string;
    expires_at: string;
};

export type PairedDevice = {
    id: string;
    name: string;
    created_at: string;
    last_seen_at?: string | null;
    revoked_at?: string | null;
};

export type PairedDeviceListResponse = {
    devices: Array<PairedDevice>;
};

export type AuthSessionCreateRequest = {
    email: string;
    password: string;
};

export type AuthSession = {
    access_token: string;
    expires_at: string;
    household_id: string;
    user_id: string;
    role: HouseholdRole;
};

export type HouseholdRole = 'owner' | 'adult' | 'viewer' | 'child';

export type RecurringFrequency = 'weekly' | 'biweekly' | 'semimonthly' | 'monthly' | 'quarterly' | 'annual';

export type Transaction = {
    id: string;
    account_id: string;
    occurred_at: string;
    amount: Money;
    merchant?: string;
    category?: string;
    description?: string;
};

export type Bill = {
    id: string;
    name: string;
    amount: Money;
    frequency: RecurringFrequency;
    next_due_date?: string;
    account_id?: string;
};

export type IncomeSource = {
    id: string;
    name: string;
    amount: Money;
    frequency: RecurringFrequency;
};

export type AccountListResponse = {
    accounts: Array<Account>;
};

export type TransactionListResponse = {
    transactions: Array<Transaction>;
};

export type BillListResponse = {
    bills: Array<Bill>;
};

export type IncomeListResponse = {
    income: Array<IncomeSource>;
};

export type GoalListResponse = {
    goals: Array<Goal>;
};

export type HouseholdContext = {
    household_id: string;
    display_name: string;
    currency: string;
    net_worth: Money;
    emergency_fund_months: number;
};

export type Account = {
    id: string;
    name: string;
    type: AccountType;
    balance: Money;
    annual_interest_rate?: number;
    minimum_payment?: Money;
    institution?: string;
    last_synced_at?: string;
};

export type AccountType = 'checking' | 'savings' | 'credit_card' | 'brokerage' | 'retirement' | 'hsa' | '529' | 'mortgage' | 'auto_loan' | 'student_loan' | 'real_estate' | 'other_asset' | 'other_liability';

export type Goal = {
    id: string;
    name: string;
    type: GoalType;
    target: Money;
    current: Money;
    target_date?: string;
    priority: number;
};

export type GoalCreateRequest = {
    name: string;
    type: GoalType;
    target: Money;
    target_date?: string;
    priority?: number;
};

export type GoalType = 'emergency_fund' | 'vacation' | 'retirement' | 'college' | 'vehicle' | 'renovation' | 'other';

export type PurchaseAdvisorRequest = {
    merchant?: string;
    item: string;
    description?: string;
    price: Money;
    source?: 'manual' | 'mobile_vision' | 'receipt' | 'product_photo';
    confidence?: number;
    user_question?: string;
};

export type RetirementScenarioRequest = {
    current_age: number;
    retirement_age: number;
    current_savings: Money;
    monthly_contribution: Money;
    annual_return_rate: number;
    annual_expenses?: Money;
};

export type Recommendation = {
    id: string;
    answer: string;
    assumptions: Array<string>;
    impacts: Array<Impact>;
    tradeoffs: Array<string>;
    alternatives: Array<string>;
    confidence: number;
    calculation_refs: Array<string>;
    warnings?: Array<string>;
    /**
     * Model id that produced the answer; null for deterministic answers
     */
    answered_by?: string;
    /**
     * Vision model that read an attached photo; null when none
     */
    photo_described_by?: string;
};

export type Impact = {
    area: 'cash_flow' | 'emergency_fund' | 'debt' | 'savings_goal' | 'retirement' | 'net_worth' | 'other';
    summary: string;
    amount?: Money;
};

export type ChatRequest = {
    conversation_id?: string;
    message: string;
    /**
     * Optional attached photo, base64-encoded (ADR 0011)
     */
    image_base64?: string;
    image_media_type?: 'image/jpeg' | 'image/png' | 'image/webp';
};

export type ChatResponse = {
    conversation_id: string;
    recommendation: Recommendation;
};

export type ImportCreateRequest = {
    source_type: ImportSourceType;
    filename: string;
    account_id?: string;
};

export type ImportRecord = {
    id: string;
    source_type: ImportSourceType;
    filename: string;
    status: 'pending' | 'processing' | 'needs_review' | 'completed' | 'discarded' | 'failed';
    error_message?: string;
    skipped_row_count?: number;
    created_at: string;
};

export type ImportListResponse = {
    imports: Array<ImportRecord>;
};

export type Document = {
    id: string;
    content_type: string;
    created_at: string;
    extraction?: DocumentExtraction;
};

export type DocumentExtraction = {
    id: string;
    extraction_type: 'pdf_text' | 'ocr';
    text: string;
    structured_fields: {
        [key: string]: unknown;
    };
    confidence: number;
    warnings: Array<string>;
    created_at: string;
};

export type DocumentListResponse = {
    documents: Array<Document>;
};

export type ImportSourceType = 'csv' | 'pdf' | 'ofx' | 'qfx';

export type ReportType = 'weekly' | 'monthly' | 'annual';

export type ExplanationSource = 'deterministic_stub' | 'llm';

export type GoalProgressSummary = {
    goal_id: string;
    name: string;
    percent_complete?: number;
    months_to_completion?: number;
    calculation_ref: string;
};

export type ReportSummary = {
    wins?: Array<string>;
    risks?: Array<string>;
    unusual_spending?: Array<string>;
    recommended_actions?: Array<string>;
    goal_progress?: Array<GoalProgressSummary>;
    net_cash_flow: Money;
    calculation_refs?: Array<string>;
};

export type Report = {
    id: string;
    report_type: ReportType;
    period_start: string;
    period_end: string;
    summary: ReportSummary;
    explanation_text: string;
    explanation_source: ExplanationSource;
    generated_at: string;
};

export type ReportListResponse = {
    reports: Array<Report>;
};

export type ReportGenerateRequest = {
    report_type: ReportType;
};

export type BackupJobStatus = 'pending' | 'running' | 'completed' | 'failed';

export type BackupJob = {
    id: string;
    status: BackupJobStatus;
    size_bytes?: number;
    error_message?: string;
    started_at: string;
    completed_at?: string;
    pruned_at?: string;
    created_at: string;
};

export type BackupJobListResponse = {
    backups: Array<BackupJob>;
};

export type HouseholdCreateRequest = {
    display_name: string;
    base_currency: string;
    owner_email: string;
    owner_password: string;
    owner_display_name: string;
};

export type Member = {
    user_id: string;
    email: string;
    display_name: string;
    role: HouseholdRole;
    created_at: string;
};

export type MemberListResponse = {
    members: Array<Member>;
};

export type MemberCreateRequest = {
    email: string;
    password: string;
    display_name: string;
    role: HouseholdRole;
};

export type MemberRoleUpdateRequest = {
    role: HouseholdRole;
};

export type AccountCreateRequest = {
    name: string;
    type: AccountType;
    currency: string;
    annual_interest_rate?: number;
    minimum_payment?: Money;
};

export type AccountUpdateRequest = {
    name?: string;
    type?: AccountType;
    annual_interest_rate?: number;
    minimum_payment?: Money;
};

export type AccountBalanceCreateRequest = {
    balance: Money;
};

export type TransactionCreateRequest = {
    account_id: string;
    occurred_at: string;
    amount: Money;
    merchant?: string;
    description?: string;
};

export type TransactionUpdateRequest = {
    account_id?: string;
    occurred_at?: string;
    amount?: Money;
    merchant?: string;
    description?: string;
};

export type BillCreateRequest = {
    name: string;
    amount: Money;
    frequency: RecurringFrequency;
    account_id?: string;
    next_due_date?: string;
};

export type BillUpdateRequest = {
    name?: string;
    amount?: Money;
    frequency?: RecurringFrequency;
    next_due_date?: string;
};

export type IncomeCreateRequest = {
    name: string;
    amount: Money;
    frequency: RecurringFrequency;
};

export type IncomeUpdateRequest = {
    name?: string;
    amount?: Money;
    frequency?: RecurringFrequency;
};

export type AuditEvent = {
    id: string;
    actor_user_id?: string;
    action: string;
    entity_type: string;
    entity_id?: string;
    summary: string;
    created_at: string;
};

export type AuditEventListResponse = {
    events: Array<AuditEvent>;
};

export type Conversation = {
    id: string;
    title: string;
    created_at: string;
    updated_at: string;
    message_count?: number;
};

export type ConversationListResponse = {
    conversations: Array<Conversation>;
};

export type ConversationMessage = {
    id: string;
    role: 'user' | 'assistant';
    content: string;
    recommendation_id?: string;
    sequence: number;
    created_at: string;
};

export type ConversationDetail = {
    id: string;
    title: string;
    created_at: string;
    updated_at: string;
    messages: Array<ConversationMessage>;
};

export type AiRuntimeConfig = {
    provider: 'vllm' | 'ollama' | 'llama_cpp' | 'openai_compatible';
    base_url: string;
    model: string;
    enabled?: boolean;
};

export type AiRuntimeStatus = {
    enabled: boolean;
    provider: string;
    model: string;
    ready: boolean;
    served_model?: string;
    detail: string;
    vision_ready?: boolean;
    vision_model?: string;
    vision_enabled?: boolean;
};

export type AiModelInfo = {
    id: string;
    label: string;
    role: 'main' | 'vision' | 'both';
    parameters_b: number;
    est_memory_gb: number;
    est_disk_gb: number;
    tool_parser?: string;
    supports_vision: boolean;
    gated: boolean;
    notes?: string;
};

export type AiModelCatalog = {
    models: Array<AiModelInfo>;
};

export type ConnectionCreateRequest = {
    provider?: 'simplefin';
    display_name: string;
    setup_token: string;
};

export type InstitutionConnection = {
    id: string;
    provider: string;
    display_name: string;
    status: string;
    last_synced_at?: string;
    last_sync_error?: string;
    created_at: string;
};

export type ConnectionListResponse = {
    connections: Array<InstitutionConnection>;
};

export type ConnectionSyncResult = {
    accounts_synced: number;
    imported: number;
    duplicates_skipped: number;
};

export type AiApplyRequest = {
    main_model: string;
    vision_model?: string;
};

export type AiSwapStatus = {
    state: 'idle' | 'running' | 'succeeded' | 'failed' | 'unavailable';
    main_model?: string;
    vision_model?: string;
    log_tail?: string;
};

export type AiHardwareProfile = {
    gpu_memory_gb?: number;
    system_memory_gb?: number;
    disk_free_gb: number;
    source: string;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Service health
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type CreatePairingSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pairing/sessions';
};

export type CreatePairingSessionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreatePairingSessionError = CreatePairingSessionErrors[keyof CreatePairingSessionErrors];

export type CreatePairingSessionResponses = {
    /**
     * Pairing session created
     */
    201: PairingSession;
};

export type CreatePairingSessionResponse = CreatePairingSessionResponses[keyof CreatePairingSessionResponses];

export type ConfirmPairingData = {
    body: PairingConfirmRequest;
    path?: never;
    query?: never;
    url: '/pairing/confirm';
};

export type ConfirmPairingErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
};

export type ConfirmPairingError = ConfirmPairingErrors[keyof ConfirmPairingErrors];

export type ConfirmPairingResponses = {
    /**
     * Device paired
     */
    200: DeviceCredential;
};

export type ConfirmPairingResponse = ConfirmPairingResponses[keyof ConfirmPairingResponses];

export type ListPairedDevicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pairing/devices';
};

export type ListPairedDevicesErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListPairedDevicesError = ListPairedDevicesErrors[keyof ListPairedDevicesErrors];

export type ListPairedDevicesResponses = {
    /**
     * Paired devices
     */
    200: PairedDeviceListResponse;
};

export type ListPairedDevicesResponse = ListPairedDevicesResponses[keyof ListPairedDevicesResponses];

export type RevokePairedDeviceData = {
    body?: never;
    path: {
        device_id: string;
    };
    query?: never;
    url: '/pairing/devices/{device_id}';
};

export type RevokePairedDeviceErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type RevokePairedDeviceError = RevokePairedDeviceErrors[keyof RevokePairedDeviceErrors];

export type RevokePairedDeviceResponses = {
    /**
     * Paired device revoked
     */
    204: void;
};

export type RevokePairedDeviceResponse = RevokePairedDeviceResponses[keyof RevokePairedDeviceResponses];

export type DeleteAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sessions';
};

export type DeleteAuthSessionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type DeleteAuthSessionError = DeleteAuthSessionErrors[keyof DeleteAuthSessionErrors];

export type DeleteAuthSessionResponses = {
    /**
     * Session revoked
     */
    204: void;
};

export type DeleteAuthSessionResponse = DeleteAuthSessionResponses[keyof DeleteAuthSessionResponses];

export type CreateAuthSessionData = {
    body: AuthSessionCreateRequest;
    path?: never;
    query?: never;
    url: '/auth/sessions';
};

export type CreateAuthSessionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type CreateAuthSessionError = CreateAuthSessionErrors[keyof CreateAuthSessionErrors];

export type CreateAuthSessionResponses = {
    /**
     * Authentication session created
     */
    201: AuthSession;
};

export type CreateAuthSessionResponse = CreateAuthSessionResponses[keyof CreateAuthSessionResponses];

export type RefreshAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sessions/refresh';
};

export type RefreshAuthSessionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type RefreshAuthSessionError = RefreshAuthSessionErrors[keyof RefreshAuthSessionErrors];

export type RefreshAuthSessionResponses = {
    /**
     * New session issued; the old token is now invalid
     */
    200: AuthSession;
};

export type RefreshAuthSessionResponse = RefreshAuthSessionResponses[keyof RefreshAuthSessionResponses];

export type CreateHouseholdData = {
    body: HouseholdCreateRequest;
    path?: never;
    query?: never;
    url: '/households';
};

export type CreateHouseholdErrors = {
    /**
     * Error response
     */
    409: ErrorResponse;
};

export type CreateHouseholdError = CreateHouseholdErrors[keyof CreateHouseholdErrors];

export type CreateHouseholdResponses = {
    /**
     * Household created; returns an authenticated session for the new owner
     */
    201: AuthSession;
};

export type CreateHouseholdResponse = CreateHouseholdResponses[keyof CreateHouseholdResponses];

export type GetHouseholdContextData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/household';
};

export type GetHouseholdContextErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type GetHouseholdContextError = GetHouseholdContextErrors[keyof GetHouseholdContextErrors];

export type GetHouseholdContextResponses = {
    /**
     * Household context
     */
    200: HouseholdContext;
};

export type GetHouseholdContextResponse = GetHouseholdContextResponses[keyof GetHouseholdContextResponses];

export type ListMembersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/household/members';
};

export type ListMembersErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListMembersError = ListMembersErrors[keyof ListMembersErrors];

export type ListMembersResponses = {
    /**
     * Household members
     */
    200: MemberListResponse;
};

export type ListMembersResponse = ListMembersResponses[keyof ListMembersResponses];

export type CreateMemberData = {
    body: MemberCreateRequest;
    path?: never;
    query?: never;
    url: '/household/members';
};

export type CreateMemberErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    409: ErrorResponse;
};

export type CreateMemberError = CreateMemberErrors[keyof CreateMemberErrors];

export type CreateMemberResponses = {
    /**
     * Member added
     */
    201: Member;
};

export type CreateMemberResponse = CreateMemberResponses[keyof CreateMemberResponses];

export type DeleteMemberData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/household/members/{user_id}';
};

export type DeleteMemberErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
    /**
     * Error response
     */
    409: ErrorResponse;
};

export type DeleteMemberError = DeleteMemberErrors[keyof DeleteMemberErrors];

export type DeleteMemberResponses = {
    /**
     * Member removed
     */
    204: void;
};

export type DeleteMemberResponse = DeleteMemberResponses[keyof DeleteMemberResponses];

export type UpdateMemberRoleData = {
    body: MemberRoleUpdateRequest;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/household/members/{user_id}';
};

export type UpdateMemberRoleErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
    /**
     * Error response
     */
    409: ErrorResponse;
};

export type UpdateMemberRoleError = UpdateMemberRoleErrors[keyof UpdateMemberRoleErrors];

export type UpdateMemberRoleResponses = {
    /**
     * Member role changed
     */
    200: Member;
};

export type UpdateMemberRoleResponse = UpdateMemberRoleResponses[keyof UpdateMemberRoleResponses];

export type ListAuditEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/audit';
};

export type ListAuditEventsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type ListAuditEventsError = ListAuditEventsErrors[keyof ListAuditEventsErrors];

export type ListAuditEventsResponses = {
    /**
     * Audit events
     */
    200: AuditEventListResponse;
};

export type ListAuditEventsResponse = ListAuditEventsResponses[keyof ListAuditEventsResponses];

export type ListAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/accounts';
};

export type ListAccountsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListAccountsError = ListAccountsErrors[keyof ListAccountsErrors];

export type ListAccountsResponses = {
    /**
     * Accounts
     */
    200: AccountListResponse;
};

export type ListAccountsResponse = ListAccountsResponses[keyof ListAccountsResponses];

export type CreateAccountData = {
    body: AccountCreateRequest;
    path?: never;
    query?: never;
    url: '/accounts';
};

export type CreateAccountErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreateAccountError = CreateAccountErrors[keyof CreateAccountErrors];

export type CreateAccountResponses = {
    /**
     * Account created
     */
    201: Account;
};

export type CreateAccountResponse = CreateAccountResponses[keyof CreateAccountResponses];

export type DeleteAccountData = {
    body?: never;
    path: {
        account_id: string;
    };
    query?: never;
    url: '/accounts/{account_id}';
};

export type DeleteAccountErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
    /**
     * Error response
     */
    409: ErrorResponse;
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
    /**
     * Account deleted
     */
    204: void;
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type UpdateAccountData = {
    body: AccountUpdateRequest;
    path: {
        account_id: string;
    };
    query?: never;
    url: '/accounts/{account_id}';
};

export type UpdateAccountErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type UpdateAccountError = UpdateAccountErrors[keyof UpdateAccountErrors];

export type UpdateAccountResponses = {
    /**
     * Account updated
     */
    200: Account;
};

export type UpdateAccountResponse = UpdateAccountResponses[keyof UpdateAccountResponses];

export type RecordAccountBalanceData = {
    body: AccountBalanceCreateRequest;
    path: {
        account_id: string;
    };
    query?: never;
    url: '/accounts/{account_id}/balances';
};

export type RecordAccountBalanceErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type RecordAccountBalanceError = RecordAccountBalanceErrors[keyof RecordAccountBalanceErrors];

export type RecordAccountBalanceResponses = {
    /**
     * Balance recorded
     */
    201: Account;
};

export type RecordAccountBalanceResponse = RecordAccountBalanceResponses[keyof RecordAccountBalanceResponses];

export type ListTransactionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/transactions';
};

export type ListTransactionsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListTransactionsError = ListTransactionsErrors[keyof ListTransactionsErrors];

export type ListTransactionsResponses = {
    /**
     * Transactions
     */
    200: TransactionListResponse;
};

export type ListTransactionsResponse = ListTransactionsResponses[keyof ListTransactionsResponses];

export type CreateTransactionData = {
    body: TransactionCreateRequest;
    path?: never;
    query?: never;
    url: '/transactions';
};

export type CreateTransactionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type CreateTransactionError = CreateTransactionErrors[keyof CreateTransactionErrors];

export type CreateTransactionResponses = {
    /**
     * Transaction created
     */
    201: Transaction;
};

export type CreateTransactionResponse = CreateTransactionResponses[keyof CreateTransactionResponses];

export type DeleteTransactionData = {
    body?: never;
    path: {
        transaction_id: string;
    };
    query?: never;
    url: '/transactions/{transaction_id}';
};

export type DeleteTransactionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DeleteTransactionError = DeleteTransactionErrors[keyof DeleteTransactionErrors];

export type DeleteTransactionResponses = {
    /**
     * Transaction deleted
     */
    204: void;
};

export type DeleteTransactionResponse = DeleteTransactionResponses[keyof DeleteTransactionResponses];

export type UpdateTransactionData = {
    body: TransactionUpdateRequest;
    path: {
        transaction_id: string;
    };
    query?: never;
    url: '/transactions/{transaction_id}';
};

export type UpdateTransactionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type UpdateTransactionError = UpdateTransactionErrors[keyof UpdateTransactionErrors];

export type UpdateTransactionResponses = {
    /**
     * Transaction updated
     */
    200: Transaction;
};

export type UpdateTransactionResponse = UpdateTransactionResponses[keyof UpdateTransactionResponses];

export type ListBillsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/bills';
};

export type ListBillsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListBillsError = ListBillsErrors[keyof ListBillsErrors];

export type ListBillsResponses = {
    /**
     * Bills
     */
    200: BillListResponse;
};

export type ListBillsResponse = ListBillsResponses[keyof ListBillsResponses];

export type CreateBillData = {
    body: BillCreateRequest;
    path?: never;
    query?: never;
    url: '/bills';
};

export type CreateBillErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreateBillError = CreateBillErrors[keyof CreateBillErrors];

export type CreateBillResponses = {
    /**
     * Bill created
     */
    201: Bill;
};

export type CreateBillResponse = CreateBillResponses[keyof CreateBillResponses];

export type DeleteBillData = {
    body?: never;
    path: {
        bill_id: string;
    };
    query?: never;
    url: '/bills/{bill_id}';
};

export type DeleteBillErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DeleteBillError = DeleteBillErrors[keyof DeleteBillErrors];

export type DeleteBillResponses = {
    /**
     * Bill deleted
     */
    204: void;
};

export type DeleteBillResponse = DeleteBillResponses[keyof DeleteBillResponses];

export type UpdateBillData = {
    body: BillUpdateRequest;
    path: {
        bill_id: string;
    };
    query?: never;
    url: '/bills/{bill_id}';
};

export type UpdateBillErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type UpdateBillError = UpdateBillErrors[keyof UpdateBillErrors];

export type UpdateBillResponses = {
    /**
     * Bill updated
     */
    200: Bill;
};

export type UpdateBillResponse = UpdateBillResponses[keyof UpdateBillResponses];

export type ListIncomeSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/income';
};

export type ListIncomeSourcesErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListIncomeSourcesError = ListIncomeSourcesErrors[keyof ListIncomeSourcesErrors];

export type ListIncomeSourcesResponses = {
    /**
     * Income sources
     */
    200: IncomeListResponse;
};

export type ListIncomeSourcesResponse = ListIncomeSourcesResponses[keyof ListIncomeSourcesResponses];

export type CreateIncomeSourceData = {
    body: IncomeCreateRequest;
    path?: never;
    query?: never;
    url: '/income';
};

export type CreateIncomeSourceErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreateIncomeSourceError = CreateIncomeSourceErrors[keyof CreateIncomeSourceErrors];

export type CreateIncomeSourceResponses = {
    /**
     * Income source created
     */
    201: IncomeSource;
};

export type CreateIncomeSourceResponse = CreateIncomeSourceResponses[keyof CreateIncomeSourceResponses];

export type DeleteIncomeSourceData = {
    body?: never;
    path: {
        income_id: string;
    };
    query?: never;
    url: '/income/{income_id}';
};

export type DeleteIncomeSourceErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DeleteIncomeSourceError = DeleteIncomeSourceErrors[keyof DeleteIncomeSourceErrors];

export type DeleteIncomeSourceResponses = {
    /**
     * Income source deleted
     */
    204: void;
};

export type DeleteIncomeSourceResponse = DeleteIncomeSourceResponses[keyof DeleteIncomeSourceResponses];

export type UpdateIncomeSourceData = {
    body: IncomeUpdateRequest;
    path: {
        income_id: string;
    };
    query?: never;
    url: '/income/{income_id}';
};

export type UpdateIncomeSourceErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type UpdateIncomeSourceError = UpdateIncomeSourceErrors[keyof UpdateIncomeSourceErrors];

export type UpdateIncomeSourceResponses = {
    /**
     * Income source updated
     */
    200: IncomeSource;
};

export type UpdateIncomeSourceResponse = UpdateIncomeSourceResponses[keyof UpdateIncomeSourceResponses];

export type ListGoalsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/goals';
};

export type ListGoalsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListGoalsError = ListGoalsErrors[keyof ListGoalsErrors];

export type ListGoalsResponses = {
    /**
     * Goals
     */
    200: GoalListResponse;
};

export type ListGoalsResponse = ListGoalsResponses[keyof ListGoalsResponses];

export type CreateGoalData = {
    body: GoalCreateRequest;
    path?: never;
    query?: never;
    url: '/goals';
};

export type CreateGoalErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreateGoalError = CreateGoalErrors[keyof CreateGoalErrors];

export type CreateGoalResponses = {
    /**
     * Goal created
     */
    201: Goal;
};

export type CreateGoalResponse = CreateGoalResponses[keyof CreateGoalResponses];

export type AnalyzePurchaseData = {
    body: PurchaseAdvisorRequest;
    path?: never;
    query?: never;
    url: '/advisor/purchase';
};

export type AnalyzePurchaseErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type AnalyzePurchaseError = AnalyzePurchaseErrors[keyof AnalyzePurchaseErrors];

export type AnalyzePurchaseResponses = {
    /**
     * Purchase recommendation
     */
    200: Recommendation;
};

export type AnalyzePurchaseResponse = AnalyzePurchaseResponses[keyof AnalyzePurchaseResponses];

export type AnalyzeRetirementData = {
    body: RetirementScenarioRequest;
    path?: never;
    query?: never;
    url: '/advisor/retirement';
};

export type AnalyzeRetirementErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type AnalyzeRetirementError = AnalyzeRetirementErrors[keyof AnalyzeRetirementErrors];

export type AnalyzeRetirementResponses = {
    /**
     * Retirement projection recommendation
     */
    200: Recommendation;
};

export type AnalyzeRetirementResponse = AnalyzeRetirementResponses[keyof AnalyzeRetirementResponses];

export type CreateChatMessageData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/chat/messages';
};

export type CreateChatMessageErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type CreateChatMessageError = CreateChatMessageErrors[keyof CreateChatMessageErrors];

export type CreateChatMessageResponses = {
    /**
     * Chat response
     */
    200: ChatResponse;
};

export type CreateChatMessageResponse = CreateChatMessageResponses[keyof CreateChatMessageResponses];

export type ListConversationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/conversations';
};

export type ListConversationsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListConversationsError = ListConversationsErrors[keyof ListConversationsErrors];

export type ListConversationsResponses = {
    /**
     * Conversations
     */
    200: ConversationListResponse;
};

export type ListConversationsResponse = ListConversationsResponses[keyof ListConversationsResponses];

export type DeleteConversationData = {
    body?: never;
    path: {
        conversation_id: string;
    };
    query?: never;
    url: '/conversations/{conversation_id}';
};

export type DeleteConversationErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DeleteConversationError = DeleteConversationErrors[keyof DeleteConversationErrors];

export type DeleteConversationResponses = {
    /**
     * Conversation deleted
     */
    204: void;
};

export type DeleteConversationResponse = DeleteConversationResponses[keyof DeleteConversationResponses];

export type GetConversationData = {
    body?: never;
    path: {
        conversation_id: string;
    };
    query?: never;
    url: '/conversations/{conversation_id}';
};

export type GetConversationErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type GetConversationError = GetConversationErrors[keyof GetConversationErrors];

export type GetConversationResponses = {
    /**
     * Conversation detail
     */
    200: ConversationDetail;
};

export type GetConversationResponse = GetConversationResponses[keyof GetConversationResponses];

export type ListImportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/imports';
};

export type ListImportsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListImportsError = ListImportsErrors[keyof ListImportsErrors];

export type ListImportsResponses = {
    /**
     * Import jobs
     */
    200: ImportListResponse;
};

export type ListImportsResponse = ListImportsResponses[keyof ListImportsResponses];

export type CreateImportData = {
    body: ImportCreateRequest;
    path?: never;
    query?: never;
    url: '/imports';
};

export type CreateImportErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type CreateImportError = CreateImportErrors[keyof CreateImportErrors];

export type CreateImportResponses = {
    /**
     * Import registered
     */
    201: ImportRecord;
};

export type CreateImportResponse = CreateImportResponses[keyof CreateImportResponses];

export type UploadImportFileData = {
    body: {
        file: Blob | File;
    };
    path: {
        import_id: string;
    };
    query?: never;
    url: '/imports/{import_id}/file';
};

export type UploadImportFileErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type UploadImportFileError = UploadImportFileErrors[keyof UploadImportFileErrors];

export type UploadImportFileResponses = {
    /**
     * File staged for background processing
     */
    202: ImportRecord;
};

export type UploadImportFileResponse = UploadImportFileResponses[keyof UploadImportFileResponses];

export type ApplyImportData = {
    body?: never;
    path: {
        import_id: string;
    };
    query?: never;
    url: '/imports/{import_id}/apply';
};

export type ApplyImportErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type ApplyImportError = ApplyImportErrors[keyof ApplyImportErrors];

export type ApplyImportResponses = {
    /**
     * Import applied
     */
    200: ImportRecord;
};

export type ApplyImportResponse = ApplyImportResponses[keyof ApplyImportResponses];

export type DiscardImportData = {
    body?: never;
    path: {
        import_id: string;
    };
    query?: never;
    url: '/imports/{import_id}/discard';
};

export type DiscardImportErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DiscardImportError = DiscardImportErrors[keyof DiscardImportErrors];

export type DiscardImportResponses = {
    /**
     * Import discarded
     */
    200: ImportRecord;
};

export type DiscardImportResponse = DiscardImportResponses[keyof DiscardImportResponses];

export type ListDocumentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/documents';
};

export type ListDocumentsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListDocumentsError = ListDocumentsErrors[keyof ListDocumentsErrors];

export type ListDocumentsResponses = {
    /**
     * Documents
     */
    200: DocumentListResponse;
};

export type ListDocumentsResponse = ListDocumentsResponses[keyof ListDocumentsResponses];

export type CreateDocumentData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/documents';
};

export type CreateDocumentErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type CreateDocumentError = CreateDocumentErrors[keyof CreateDocumentErrors];

export type CreateDocumentResponses = {
    /**
     * Document created and extracted
     */
    201: Document;
};

export type CreateDocumentResponse = CreateDocumentResponses[keyof CreateDocumentResponses];

export type ListReportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reports';
};

export type ListReportsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListReportsError = ListReportsErrors[keyof ListReportsErrors];

export type ListReportsResponses = {
    /**
     * Reports
     */
    200: ReportListResponse;
};

export type ListReportsResponse = ListReportsResponses[keyof ListReportsResponses];

export type GetReportData = {
    body?: never;
    path: {
        report_id: string;
    };
    query?: never;
    url: '/reports/{report_id}';
};

export type GetReportErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type GetReportError = GetReportErrors[keyof GetReportErrors];

export type GetReportResponses = {
    /**
     * Report
     */
    200: Report;
};

export type GetReportResponse = GetReportResponses[keyof GetReportResponses];

export type GenerateReportData = {
    body: ReportGenerateRequest;
    path?: never;
    query?: never;
    url: '/reports/generate';
};

export type GenerateReportErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type GenerateReportError = GenerateReportErrors[keyof GenerateReportErrors];

export type GenerateReportResponses = {
    /**
     * Report generated
     */
    201: Report;
};

export type GenerateReportResponse = GenerateReportResponses[keyof GenerateReportResponses];

export type ListBackupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/backups';
};

export type ListBackupsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type ListBackupsError = ListBackupsErrors[keyof ListBackupsErrors];

export type ListBackupsResponses = {
    /**
     * Backup jobs
     */
    200: BackupJobListResponse;
};

export type ListBackupsResponse = ListBackupsResponses[keyof ListBackupsResponses];

export type CreateBackupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/backups';
};

export type CreateBackupErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreateBackupError = CreateBackupErrors[keyof CreateBackupErrors];

export type CreateBackupResponses = {
    /**
     * Backup created
     */
    201: BackupJob;
};

export type CreateBackupResponse = CreateBackupResponses[keyof CreateBackupResponses];

export type RestoreBackupData = {
    body?: never;
    path: {
        backup_id: string;
    };
    query?: never;
    url: '/backups/{backup_id}/restore';
};

export type RestoreBackupErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type RestoreBackupError = RestoreBackupErrors[keyof RestoreBackupErrors];

export type RestoreBackupResponses = {
    /**
     * Backup restored
     */
    200: BackupJob;
};

export type RestoreBackupResponse = RestoreBackupResponses[keyof RestoreBackupResponses];

export type GetAiRuntimeConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ai/runtime';
};

export type GetAiRuntimeConfigErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type GetAiRuntimeConfigError = GetAiRuntimeConfigErrors[keyof GetAiRuntimeConfigErrors];

export type GetAiRuntimeConfigResponses = {
    /**
     * AI runtime configuration
     */
    200: AiRuntimeConfig;
};

export type GetAiRuntimeConfigResponse = GetAiRuntimeConfigResponses[keyof GetAiRuntimeConfigResponses];

export type UpdateAiRuntimeConfigData = {
    body: AiRuntimeConfig;
    path?: never;
    query?: never;
    url: '/ai/runtime';
};

export type UpdateAiRuntimeConfigErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type UpdateAiRuntimeConfigError = UpdateAiRuntimeConfigErrors[keyof UpdateAiRuntimeConfigErrors];

export type UpdateAiRuntimeConfigResponses = {
    /**
     * AI runtime configuration
     */
    200: AiRuntimeConfig;
};

export type UpdateAiRuntimeConfigResponse = UpdateAiRuntimeConfigResponses[keyof UpdateAiRuntimeConfigResponses];

export type GetAiRuntimeStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ai/runtime/status';
};

export type GetAiRuntimeStatusErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type GetAiRuntimeStatusError = GetAiRuntimeStatusErrors[keyof GetAiRuntimeStatusErrors];

export type GetAiRuntimeStatusResponses = {
    /**
     * AI runtime status
     */
    200: AiRuntimeStatus;
};

export type GetAiRuntimeStatusResponse = GetAiRuntimeStatusResponses[keyof GetAiRuntimeStatusResponses];

export type ListAiModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ai/models';
};

export type ListAiModelsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListAiModelsError = ListAiModelsErrors[keyof ListAiModelsErrors];

export type ListAiModelsResponses = {
    /**
     * Curated model catalog
     */
    200: AiModelCatalog;
};

export type ListAiModelsResponse = ListAiModelsResponses[keyof ListAiModelsResponses];

export type GetAiHardwareProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ai/hardware';
};

export type GetAiHardwareProfileErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type GetAiHardwareProfileError = GetAiHardwareProfileErrors[keyof GetAiHardwareProfileErrors];

export type GetAiHardwareProfileResponses = {
    /**
     * Hardware profile
     */
    200: AiHardwareProfile;
};

export type GetAiHardwareProfileResponse = GetAiHardwareProfileResponses[keyof GetAiHardwareProfileResponses];

export type SearchAiModelsData = {
    body?: never;
    path?: never;
    query: {
        q: string;
    };
    url: '/ai/models/search';
};

export type SearchAiModelsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    503: ErrorResponse;
};

export type SearchAiModelsError = SearchAiModelsErrors[keyof SearchAiModelsErrors];

export type SearchAiModelsResponses = {
    /**
     * Search results mapped to catalog shape
     */
    200: AiModelCatalog;
};

export type SearchAiModelsResponse = SearchAiModelsResponses[keyof SearchAiModelsResponses];

export type ApplyAiModelSelectionData = {
    body: AiApplyRequest;
    path?: never;
    query?: never;
    url: '/ai/runtime/apply';
};

export type ApplyAiModelSelectionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    409: ErrorResponse;
    /**
     * Error response
     */
    503: ErrorResponse;
};

export type ApplyAiModelSelectionError = ApplyAiModelSelectionErrors[keyof ApplyAiModelSelectionErrors];

export type ApplyAiModelSelectionResponses = {
    /**
     * Swap started
     */
    202: AiSwapStatus;
};

export type ApplyAiModelSelectionResponse = ApplyAiModelSelectionResponses[keyof ApplyAiModelSelectionResponses];

export type GetAiApplyStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ai/runtime/apply/status';
};

export type GetAiApplyStatusErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type GetAiApplyStatusError = GetAiApplyStatusErrors[keyof GetAiApplyStatusErrors];

export type GetAiApplyStatusResponses = {
    /**
     * Swap status
     */
    200: AiSwapStatus;
};

export type GetAiApplyStatusResponse = GetAiApplyStatusResponses[keyof GetAiApplyStatusResponses];

export type ListConnectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connections';
};

export type ListConnectionsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListConnectionsError = ListConnectionsErrors[keyof ListConnectionsErrors];

export type ListConnectionsResponses = {
    /**
     * Linked institutions
     */
    200: ConnectionListResponse;
};

export type ListConnectionsResponse = ListConnectionsResponses[keyof ListConnectionsResponses];

export type CreateConnectionData = {
    body: ConnectionCreateRequest;
    path?: never;
    query?: never;
    url: '/connections';
};

export type CreateConnectionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    422: ErrorResponse;
    /**
     * Error response
     */
    503: ErrorResponse;
};

export type CreateConnectionError = CreateConnectionErrors[keyof CreateConnectionErrors];

export type CreateConnectionResponses = {
    /**
     * Institution linked
     */
    201: InstitutionConnection;
};

export type CreateConnectionResponse = CreateConnectionResponses[keyof CreateConnectionResponses];

export type DeleteConnectionData = {
    body?: never;
    path: {
        connection_id: string;
    };
    query?: never;
    url: '/connections/{connection_id}';
};

export type DeleteConnectionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DeleteConnectionError = DeleteConnectionErrors[keyof DeleteConnectionErrors];

export type DeleteConnectionResponses = {
    /**
     * Connection removed
     */
    204: void;
};

export type DeleteConnectionResponse = DeleteConnectionResponses[keyof DeleteConnectionResponses];

export type SyncConnectionData = {
    body?: never;
    path: {
        connection_id: string;
    };
    query?: never;
    url: '/connections/{connection_id}/sync';
};

export type SyncConnectionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
    /**
     * Error response
     */
    502: ErrorResponse;
};

export type SyncConnectionError = SyncConnectionErrors[keyof SyncConnectionErrors];

export type SyncConnectionResponses = {
    /**
     * Sync result
     */
    200: ConnectionSyncResult;
};

export type SyncConnectionResponse = SyncConnectionResponses[keyof SyncConnectionResponses];
