// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type HealthResponse = {
    status: 'ok' | 'degraded';
    version: string;
};

export type ErrorResponse = {
    error: {
        code: string;
        message: string;
        details?: {
            [key: string]: unknown;
        };
    };
};

export type Money = {
    /**
     * Signed integer amount in minor currency units.
     */
    amount_minor: number;
    currency: string;
};

export type PairingSession = {
    id: string;
    qr_payload: string;
    expires_at: string;
};

export type PairingConfirmRequest = {
    pairing_session_id: string;
    device_name: string;
    device_public_key: string;
};

export type DeviceCredential = {
    device_id: string;
    access_token: string;
    expires_at: string;
};

export type PairedDevice = {
    id: string;
    name: string;
    created_at: string;
    last_seen_at?: string | null;
    revoked_at?: string | null;
};

export type PairedDeviceListResponse = {
    devices: Array<PairedDevice>;
};

export type AuthSessionCreateRequest = {
    email: string;
    password: string;
};

export type AuthSession = {
    access_token: string;
    expires_at: string;
    household_id: string;
    user_id: string;
    role: HouseholdRole;
};

export type HouseholdRole = 'owner' | 'adult' | 'viewer' | 'child';

export type RecurringFrequency = 'weekly' | 'biweekly' | 'semimonthly' | 'monthly' | 'quarterly' | 'annual';

export type Transaction = {
    id: string;
    account_id: string;
    occurred_at: string;
    amount: Money;
    merchant?: string;
    category?: string;
    description?: string;
};

export type Bill = {
    id: string;
    name: string;
    amount: Money;
    frequency: RecurringFrequency;
    next_due_date?: string;
    account_id?: string;
};

export type IncomeSource = {
    id: string;
    name: string;
    amount: Money;
    frequency: RecurringFrequency;
};

export type AccountListResponse = {
    accounts: Array<Account>;
};

export type TransactionListResponse = {
    transactions: Array<Transaction>;
};

export type BillListResponse = {
    bills: Array<Bill>;
};

export type IncomeListResponse = {
    income: Array<IncomeSource>;
};

export type GoalListResponse = {
    goals: Array<Goal>;
};

export type HouseholdContext = {
    household_id: string;
    display_name: string;
    currency: string;
    net_worth: Money;
    emergency_fund_months: number;
};

export type Account = {
    id: string;
    name: string;
    type: AccountType;
    balance: Money;
};

export type AccountType = 'checking' | 'savings' | 'credit_card' | 'brokerage' | 'retirement' | 'hsa' | 529 | 'mortgage' | 'auto_loan' | 'student_loan' | 'real_estate' | 'other_asset' | 'other_liability';

export type Goal = {
    id: string;
    name: string;
    type: GoalType;
    target: Money;
    current: Money;
    target_date?: string;
    priority: number;
};

export type GoalCreateRequest = {
    name: string;
    type: GoalType;
    target: Money;
    target_date?: string;
    priority?: number;
};

export type GoalType = 'emergency_fund' | 'vacation' | 'retirement' | 'college' | 'vehicle' | 'renovation' | 'other';

export type PurchaseAdvisorRequest = {
    merchant?: string;
    item: string;
    description?: string;
    price: Money;
    source?: 'manual' | 'mobile_vision' | 'receipt' | 'product_photo';
    confidence?: number;
    user_question?: string;
};

export type Recommendation = {
    id: string;
    answer: string;
    assumptions: Array<string>;
    impacts: Array<Impact>;
    tradeoffs: Array<string>;
    alternatives: Array<string>;
    confidence: number;
    calculation_refs: Array<string>;
    warnings?: Array<string>;
};

export type Impact = {
    area: 'cash_flow' | 'emergency_fund' | 'debt' | 'savings_goal' | 'retirement' | 'net_worth' | 'other';
    summary: string;
    amount?: Money;
};

export type ChatRequest = {
    conversation_id?: string;
    message: string;
};

export type ChatResponse = {
    conversation_id: string;
    recommendation: Recommendation;
};

export type ImportCreateRequest = {
    source_type: ImportSourceType;
    filename: string;
    account_id?: string;
};

export type ImportRecord = {
    id: string;
    source_type: ImportSourceType;
    filename: string;
    status: 'pending' | 'processing' | 'needs_review' | 'completed' | 'failed';
    created_at: string;
};

export type ImportSourceType = 'csv' | 'pdf' | 'ofx' | 'qfx';

export type ReportSummary = {
    id: string;
    type: ReportType;
    period_start: string;
    period_end: string;
    title: string;
};

export type ReportType = 'weekly' | 'monthly' | 'annual';

export type AiRuntimeConfig = {
    provider: 'vllm' | 'ollama' | 'llama_cpp' | 'openai_compatible';
    base_url: string;
    model: string;
    enabled?: boolean;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Service health
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type CreatePairingSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pairing/sessions';
};

export type CreatePairingSessionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreatePairingSessionError = CreatePairingSessionErrors[keyof CreatePairingSessionErrors];

export type CreatePairingSessionResponses = {
    /**
     * Pairing session created
     */
    201: PairingSession;
};

export type CreatePairingSessionResponse = CreatePairingSessionResponses[keyof CreatePairingSessionResponses];

export type ConfirmPairingData = {
    body: PairingConfirmRequest;
    path?: never;
    query?: never;
    url: '/pairing/confirm';
};

export type ConfirmPairingErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
};

export type ConfirmPairingError = ConfirmPairingErrors[keyof ConfirmPairingErrors];

export type ConfirmPairingResponses = {
    /**
     * Device paired
     */
    200: DeviceCredential;
};

export type ConfirmPairingResponse = ConfirmPairingResponses[keyof ConfirmPairingResponses];

export type ListPairedDevicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pairing/devices';
};

export type ListPairedDevicesErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListPairedDevicesError = ListPairedDevicesErrors[keyof ListPairedDevicesErrors];

export type ListPairedDevicesResponses = {
    /**
     * Paired devices
     */
    200: PairedDeviceListResponse;
};

export type ListPairedDevicesResponse = ListPairedDevicesResponses[keyof ListPairedDevicesResponses];

export type RevokePairedDeviceData = {
    body?: never;
    path: {
        device_id: string;
    };
    query?: never;
    url: '/pairing/devices/{device_id}';
};

export type RevokePairedDeviceErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type RevokePairedDeviceError = RevokePairedDeviceErrors[keyof RevokePairedDeviceErrors];

export type RevokePairedDeviceResponses = {
    /**
     * Paired device revoked
     */
    204: void;
};

export type RevokePairedDeviceResponse = RevokePairedDeviceResponses[keyof RevokePairedDeviceResponses];

export type CreateAuthSessionData = {
    body: AuthSessionCreateRequest;
    path?: never;
    query?: never;
    url: '/auth/sessions';
};

export type CreateAuthSessionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type CreateAuthSessionError = CreateAuthSessionErrors[keyof CreateAuthSessionErrors];

export type CreateAuthSessionResponses = {
    /**
     * Authentication session created
     */
    201: AuthSession;
};

export type CreateAuthSessionResponse = CreateAuthSessionResponses[keyof CreateAuthSessionResponses];

export type GetHouseholdContextData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/household';
};

export type GetHouseholdContextErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type GetHouseholdContextError = GetHouseholdContextErrors[keyof GetHouseholdContextErrors];

export type GetHouseholdContextResponses = {
    /**
     * Household context
     */
    200: HouseholdContext;
};

export type GetHouseholdContextResponse = GetHouseholdContextResponses[keyof GetHouseholdContextResponses];

export type ListAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/accounts';
};

export type ListAccountsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListAccountsError = ListAccountsErrors[keyof ListAccountsErrors];

export type ListAccountsResponses = {
    /**
     * Accounts
     */
    200: AccountListResponse;
};

export type ListAccountsResponse = ListAccountsResponses[keyof ListAccountsResponses];

export type ListTransactionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/transactions';
};

export type ListTransactionsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListTransactionsError = ListTransactionsErrors[keyof ListTransactionsErrors];

export type ListTransactionsResponses = {
    /**
     * Transactions
     */
    200: TransactionListResponse;
};

export type ListTransactionsResponse = ListTransactionsResponses[keyof ListTransactionsResponses];

export type ListBillsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/bills';
};

export type ListBillsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListBillsError = ListBillsErrors[keyof ListBillsErrors];

export type ListBillsResponses = {
    /**
     * Bills
     */
    200: BillListResponse;
};

export type ListBillsResponse = ListBillsResponses[keyof ListBillsResponses];

export type ListIncomeSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/income';
};

export type ListIncomeSourcesErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListIncomeSourcesError = ListIncomeSourcesErrors[keyof ListIncomeSourcesErrors];

export type ListIncomeSourcesResponses = {
    /**
     * Income sources
     */
    200: IncomeListResponse;
};

export type ListIncomeSourcesResponse = ListIncomeSourcesResponses[keyof ListIncomeSourcesResponses];

export type ListGoalsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/goals';
};

export type ListGoalsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListGoalsError = ListGoalsErrors[keyof ListGoalsErrors];

export type ListGoalsResponses = {
    /**
     * Goals
     */
    200: GoalListResponse;
};

export type ListGoalsResponse = ListGoalsResponses[keyof ListGoalsResponses];

export type CreateGoalData = {
    body: GoalCreateRequest;
    path?: never;
    query?: never;
    url: '/goals';
};

export type CreateGoalErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreateGoalError = CreateGoalErrors[keyof CreateGoalErrors];

export type CreateGoalResponses = {
    /**
     * Goal created
     */
    201: Goal;
};

export type CreateGoalResponse = CreateGoalResponses[keyof CreateGoalResponses];

export type AnalyzePurchaseData = {
    body: PurchaseAdvisorRequest;
    path?: never;
    query?: never;
    url: '/advisor/purchase';
};

export type AnalyzePurchaseErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type AnalyzePurchaseError = AnalyzePurchaseErrors[keyof AnalyzePurchaseErrors];

export type AnalyzePurchaseResponses = {
    /**
     * Purchase recommendation
     */
    200: Recommendation;
};

export type AnalyzePurchaseResponse = AnalyzePurchaseResponses[keyof AnalyzePurchaseResponses];

export type CreateChatMessageData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/chat/messages';
};

export type CreateChatMessageErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type CreateChatMessageError = CreateChatMessageErrors[keyof CreateChatMessageErrors];

export type CreateChatMessageResponses = {
    /**
     * Chat response
     */
    200: ChatResponse;
};

export type CreateChatMessageResponse = CreateChatMessageResponses[keyof CreateChatMessageResponses];

export type ListImportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/imports';
};

export type ListImportsResponses = {
    /**
     * Import jobs
     */
    200: {
        imports: Array<ImportRecord>;
    };
};

export type ListImportsResponse = ListImportsResponses[keyof ListImportsResponses];

export type CreateImportData = {
    body: ImportCreateRequest;
    path?: never;
    query?: never;
    url: '/imports';
};

export type CreateImportResponses = {
    /**
     * Import accepted
     */
    202: ImportRecord;
};

export type CreateImportResponse = CreateImportResponses[keyof CreateImportResponses];

export type ListReportsData = {
    body?: never;
    path?: never;
    query?: {
        type?: ReportType;
    };
    url: '/reports';
};

export type ListReportsResponses = {
    /**
     * Reports
     */
    200: {
        reports: Array<ReportSummary>;
    };
};

export type ListReportsResponse = ListReportsResponses[keyof ListReportsResponses];

export type GetAiRuntimeConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ai/runtime';
};

export type GetAiRuntimeConfigErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type GetAiRuntimeConfigError = GetAiRuntimeConfigErrors[keyof GetAiRuntimeConfigErrors];

export type GetAiRuntimeConfigResponses = {
    /**
     * AI runtime configuration
     */
    200: AiRuntimeConfig;
};

export type GetAiRuntimeConfigResponse = GetAiRuntimeConfigResponses[keyof GetAiRuntimeConfigResponses];

export type UpdateAiRuntimeConfigData = {
    body: AiRuntimeConfig;
    path?: never;
    query?: never;
    url: '/ai/runtime';
};

export type UpdateAiRuntimeConfigErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type UpdateAiRuntimeConfigError = UpdateAiRuntimeConfigErrors[keyof UpdateAiRuntimeConfigErrors];

export type UpdateAiRuntimeConfigResponses = {
    /**
     * AI runtime configuration
     */
    200: AiRuntimeConfig;
};

export type UpdateAiRuntimeConfigResponse = UpdateAiRuntimeConfigResponses[keyof UpdateAiRuntimeConfigResponses];
