// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type HealthResponse = {
    status: 'ok' | 'degraded';
    version: string;
};

export type ErrorResponse = {
    error: {
        code: string;
        message: string;
        details?: {
            [key: string]: unknown;
        };
    };
};

export type Money = {
    /**
     * Signed integer amount in minor currency units.
     */
    amount_minor: number;
    currency: string;
};

export type PairingSession = {
    id: string;
    qr_payload: string;
    expires_at: string;
};

export type PairingConfirmRequest = {
    pairing_session_id: string;
    device_name: string;
    device_public_key: string;
};

export type DeviceCredential = {
    device_id: string;
    access_token: string;
    expires_at: string;
    /**
     * M83: household role of the user the device acts as (the pairing session's creator), so the mobile app can build its role-aware shell without spending the device token on a session refresh.
     */
    role?: HouseholdRole;
};

export type PairedDevice = {
    id: string;
    name: string;
    created_at: string;
    last_seen_at?: string | null;
    revoked_at?: string | null;
};

export type PairedDeviceListResponse = {
    devices: Array<PairedDevice>;
};

export type AuthSessionCreateRequest = {
    email: string;
    password: string;
};

export type AuthSession = {
    access_token: string;
    expires_at: string;
    household_id: string;
    user_id: string;
    role: HouseholdRole;
};

export type HouseholdRole = 'owner' | 'adult' | 'viewer' | 'child';

export type RecurringFrequency = 'weekly' | 'biweekly' | 'semimonthly' | 'monthly' | 'quarterly' | 'annual';

export type Transaction = {
    id: string;
    account_id: string;
    occurred_at: string;
    amount: Money;
    merchant?: string;
    category?: string;
    category_id?: string;
    description?: string;
};

export type Category = {
    id: string;
    name: string;
};

export type CategoryListResponse = {
    categories: Array<Category>;
};

export type CategoryCreateRequest = {
    name: string;
};

export type Bill = {
    id: string;
    name: string;
    amount: Money;
    frequency: RecurringFrequency;
    next_due_date?: string;
    account_id?: string;
};

export type IncomeSource = {
    id: string;
    name: string;
    amount: Money;
    frequency: RecurringFrequency;
};

export type AccountListResponse = {
    accounts: Array<Account>;
};

export type TransactionListResponse = {
    transactions: Array<Transaction>;
};

export type BillListResponse = {
    bills: Array<Bill>;
};

/**
 * A recurring charge detected in checking/credit-card transactions (M58). Deterministic pattern-matching, not an AI guess — every suggestion is explainable as "N charges of ~amount at ~cadence".
 *
 */
export type BillSuggestion = {
    /**
     * Normalized merchant identifier; used to dismiss.
     */
    merchant_key: string;
    name: string;
    amount: Money;
    frequency: RecurringFrequency;
    next_due_date: string;
    occurrences: number;
    last_seen: string;
};

/**
 * An existing bill whose live charge pattern has drifted (M59): the detected median amount or cadence no longer matches the stored bill. Applying it is always a user-confirmed PATCH — never silent.
 *
 */
export type BillUpdateSuggestion = {
    bill_id: string;
    name: string;
    /**
     * Pass to the dismissal endpoint to mute THIS suggested value; a later different value prompts again.
     *
     */
    dismiss_key: string;
    current_amount: Money;
    suggested_amount: Money;
    frequency: RecurringFrequency;
    next_due_date: string;
    occurrences: number;
    last_seen: string;
};

export type BillSuggestionListResponse = {
    suggestions: Array<BillSuggestion>;
    updates: Array<BillUpdateSuggestion>;
};

export type BillSuggestionDismissRequest = {
    merchant_key: string;
};

/**
 * A durable household fact the advisor remembers across conversations (M57, ADR 0016). Facts survive conversation deletion by design; deleting the memory itself is the forget operation.
 *
 */
export type Memory = {
    id: string;
    /**
     * Stable identifier; a restated fact updates, not duplicates.
     */
    key: string;
    value: string;
    source: 'chat' | 'manual';
    created_at: string;
    updated_at: string;
};

export type MemoryListResponse = {
    memories: Array<Memory>;
};

export type MemoryCreateRequest = {
    value: string;
};

export type IncomeAnalysisTransaction = {
    transaction_id: string;
    occurred_at: string;
    amount: Money;
    name: string;
    /**
     * The payer/sender as the bank reported it.
     */
    merchant?: string;
    /**
     * Full untruncated bank memo (often names the source account).
     */
    description?: string;
    /**
     * The checking account the deposit landed in.
     */
    account_name?: string;
    excluded: boolean;
};

/**
 * A recurring deposit pattern detected in checking accounts (M61) with every underlying transaction shown as editable evidence.
 *
 */
export type IncomeSourceAnalysis = {
    source_key: string;
    name: string;
    /**
     * Detected cadence, or "irregular" for manually-added deposits.
     */
    frequency: string;
    manually_added: boolean;
    typical_amount: Money;
    total_amount: Money;
    transactions: Array<IncomeAnalysisTransaction>;
};

export type IncomeRollup = {
    annual_income: Money;
    monthly_average: Money;
    transaction_count: number;
    window_days: number;
    /**
     * Earliest synced checking transaction in the window.
     */
    coverage_start?: string;
    /**
     * How many days of history the analysis actually has.
     */
    coverage_days?: number;
};

/**
 * Deterministic US federal + FICA estimate with explicit assumptions (standard deduction only, no credits, no state tax). When income is treated as take-home, gross is recovered by solving gross − tax(gross) = net.
 *
 */
export type TaxEstimate = {
    tax_year: number;
    filing_status: 'single' | 'married_joint' | 'head_of_household';
    income_treated_as_net: boolean;
    /**
     * USPS state code used for state income tax (M65).
     */
    state?: string;
    gross_income: Money;
    net_income?: Money;
    standard_deduction: Money;
    taxable_income: Money;
    federal_income_tax: Money;
    fica_tax: Money;
    state_income_tax?: Money;
    total_tax: Money;
    effective_rate: number;
    assumptions: Array<string>;
};

export type IncomeEarner = {
    id: string;
    label: string;
    base_salary: Money;
    rsu_annual: Money;
    rsu_frequency?: 'monthly' | 'quarterly' | 'semiannual' | 'annual';
    rsu_next_vest_date?: string;
    bonus_percent?: number;
    bonus_month?: number;
    w2_year?: number;
    w2_wages?: Money;
    w2_withheld?: Money;
};

export type ExpectedIncomeEvent = {
    date: string;
    label: string;
    amount: Money;
};

/**
 * Declared compensation (M73). When present it is the authority for the tax estimate — no net-to-gross inference.
 *
 */
export type IncomeProfile = {
    earners: Array<IncomeEarner>;
    expected_annual_gross: Money;
    expected_events: Array<ExpectedIncomeEvent>;
};

export type IncomeEarnerCreateRequest = {
    label: string;
    base_salary_minor?: number;
    rsu_annual_minor?: number;
    rsu_frequency?: 'monthly' | 'quarterly' | 'semiannual' | 'annual';
    rsu_next_vest_date?: string;
    bonus_percent?: number;
    bonus_month?: number;
    w2_year?: number;
    w2_wages_minor?: number;
    w2_withheld_minor?: number;
};

export type W2ScanRequest = {
    image_base64: string;
    image_media_type: 'image/jpeg' | 'image/png' | 'image/webp' | 'application/pdf';
};

/**
 * Candidate values only — the user confirms before anything is saved.
 */
export type W2ScanResult = {
    year?: number;
    employer?: string;
    wages_minor?: number;
    federal_withheld_minor?: number;
    note: string;
};

export type IncomeAnalysisResponse = {
    sources: Array<IncomeSourceAnalysis>;
    other_inflows: Array<IncomeAnalysisTransaction>;
    rollup: IncomeRollup;
    profile?: IncomeProfile;
    /**
     * Present when the synced history does not span the full analysis window (e.g. it starts mid-year) — income and tax are then likely underestimated. Internal transfers between the household's own accounts are never shown or counted (M63).
     *
     */
    coverage_warning?: string;
    tax: TaxEstimate;
};

export type IncomeOverrideRequest = {
    transaction_id: string;
    verdict: 'include' | 'exclude' | 'clear';
};

export type IncomeTaxSettingsRequest = {
    tax_filing_status: 'single' | 'married_joint' | 'head_of_household';
    income_treated_as_net: boolean;
    /**
     * USPS state code for state income tax (M65). Only the state is collected — never a street address. Null clears it.
     *
     */
    state?: string;
};

export type IncomeListResponse = {
    income: Array<IncomeSource>;
};

export type GoalListResponse = {
    goals: Array<Goal>;
};

export type HouseholdContext = {
    household_id: string;
    display_name: string;
    currency: string;
    net_worth: Money;
    emergency_fund_months: number;
    /**
     * M38: emergency-fund coverage vs the standard 3–6 month guidance.
     */
    emergency_fund?: EmergencyFundSummary;
    /**
     * M38: recurring income vs bills, normalized monthly.
     */
    monthly_cash_flow?: MonthlyCashFlow;
    /**
     * M38: positive balances grouped by spendability category (ordered).
     */
    asset_breakdown?: Array<AssetCategoryTotal>;
    /**
     * M38: positive sum of all negative account balances.
     */
    total_debt?: Money;
    /**
     * M39: bills due within the next 14 days, soonest first.
     */
    upcoming_bills?: Array<UpcomingBill>;
    /**
     * M40: recent net-worth snapshots, oldest-first, for the trend sparkline.
     */
    net_worth_history?: Array<NetWorthPoint>;
    /**
     * M41: the highest-priority savings goal with progress, when one exists.
     */
    top_goal?: GoalProgress;
    /**
     * M42: month-to-date spending vs the same period last month, plus top merchants.
     */
    spending_insights?: SpendingInsights;
    /**
     * M44: recurring income vs trailing-3-month average actual spending.
     */
    savings_rate?: SavingsRate;
    /**
     * M46: envelope health (over/warning counts, budgeted vs spent); absent when no budgets exist.
     */
    budget_summary?: BudgetSummary;
    /**
     * M93: liquid cash minus the emergency fund, bills due, and minimum debt payments — what's actually free to spend right now.
     */
    safe_to_spend?: SafeToSpend;
};

export type Budget = {
    id: string;
    category_id: string;
    category_name: string;
    limit: Money;
    /**
     * Outflow in this category during the current calendar month.
     */
    spent: Money;
    /**
     * limit − spent; negative when over budget.
     */
    remaining: Money;
    /**
     * Raw spent/limit percent; may exceed 100.
     */
    percent_used: number;
    status: 'under' | 'warning' | 'over';
};

export type BudgetListResponse = {
    budgets: Array<Budget>;
};

export type BudgetCreateRequest = {
    category_id: string;
    limit: Money;
};

export type BudgetUpdateRequest = {
    limit: Money;
};

export type BudgetSummary = {
    envelope_count: number;
    over_count: number;
    /**
     * Envelopes at ≥80% of their limit (but not over).
     */
    warning_count: number;
    total_budgeted: Money;
    total_spent: Money;
};

/**
 * M93: money actually free to spend now — liquid cash net of the emergency fund, bills due, and minimum debt payments. Income during the window is NOT counted.
 */
export type SafeToSpend = {
    /**
     * Checking + savings only (never retirement/education funds).
     */
    liquid_balance: Money;
    /**
     * Money explicitly designated for emergencies; held back.
     */
    emergency_fund_reserved: Money;
    /**
     * Bills falling due within the horizon.
     */
    bills_due: Money;
    /**
     * Minimum payments owed on liability accounts with recorded terms.
     */
    minimum_debt_payments: Money;
    /**
     * emergency_fund_reserved + bills_due + minimum_debt_payments.
     */
    committed_total: Money;
    /**
     * liquid_balance − committed_total. May be negative.
     */
    safe_to_spend: Money;
    /**
     * All liabilities as a positive amount — reported, never subtracted, so spendable cash is never shown without the debt beside it.
     */
    total_debt: Money;
    /**
     * Human-readable caveats (e.g. debts with no recorded minimum payment understate what's committed).
     */
    warnings: Array<string>;
};

export type SavingsRate = {
    /**
     * (income - avg spending) / income, %; null when income is 0; may be negative.
     */
    percent?: number;
    monthly_income: Money;
    average_monthly_spending: Money;
};

export type SpendingInsights = {
    this_month: Money;
    last_month: Money;
    /**
     * Percent change vs last month; null when last month was zero.
     */
    change_percent?: number;
    top_merchants?: Array<MerchantSpend>;
};

export type MerchantSpend = {
    merchant: string;
    amount: Money;
};

export type GoalProgress = {
    id: string;
    name: string;
    type: GoalType;
    current: Money;
    target: Money;
    /**
     * current / target, 0-100 (capped), 0 when target is 0.
     */
    percent_complete: number;
    target_date?: string;
};

export type NetWorthPoint = {
    as_of: string;
    net_worth: Money;
};

export type UpcomingBill = {
    id: string;
    name: string;
    amount: Money;
    due_date: string;
    /**
     * Whole days from today to the next occurrence (0 = due today).
     */
    days_until: number;
};

export type EmergencyFundSummary = {
    /**
     * Months of expenses the fund covers; null when there are no bills.
     */
    months?: number;
    /**
     * The fund balance used — designated total when set, else all liquid money.
     */
    reserved: Money;
    /**
     * True when the fund comes from explicit account designations (M36).
     */
    using_designations: boolean;
    monthly_expenses: Money;
    target_months_min: number;
    target_months_recommended: number;
    /**
     * Money still needed to reach the recommended target; 0 when funded, absent when no bills.
     */
    gap_to_recommended?: Money;
    /**
     * The household's own emergency_fund goal target (M75); the status is the more conservative of months-coverage and goal progress.
     *
     */
    goal_target?: Money;
    status: 'no_bills' | 'no_fund' | 'getting_started' | 'on_track' | 'fully_funded';
};

export type MonthlyCashFlow = {
    income: Money;
    bills: Money;
    /**
     * Income minus bills; excludes discretionary spending.
     */
    net: Money;
};

export type AssetCategoryTotal = {
    category: 'liquid' | 'investments' | 'retirement' | 'education' | 'property';
    total: Money;
};

export type Account = {
    id: string;
    name: string;
    type: AccountType;
    balance: Money;
    annual_interest_rate?: number;
    minimum_payment?: Money;
    institution?: string;
    last_synced_at?: string;
    /**
     * M36: percent of this account's balance reserved for emergencies (exclusive with emergency_fund_amount).
     */
    emergency_fund_percent?: number;
    /**
     * M36: fixed amount of this account reserved for emergencies (exclusive with emergency_fund_percent).
     */
    emergency_fund_amount?: Money;
    /**
     * M36: derived reservation — percent of the latest balance or the fixed amount, capped at the balance.
     */
    emergency_fund_reserved?: Money;
};

export type AccountType = 'checking' | 'savings' | 'credit_card' | 'brokerage' | 'retirement' | 'hsa' | '529' | 'mortgage' | 'auto_loan' | 'student_loan' | 'real_estate' | 'other_asset' | 'other_liability';

export type Goal = {
    id: string;
    name: string;
    type: GoalType;
    target: Money;
    current: Money;
    target_date?: string;
    priority: number;
};

export type GoalCreateRequest = {
    name: string;
    type: GoalType;
    target: Money;
    target_date?: string;
    priority?: number;
};

export type GoalType = 'emergency_fund' | 'vacation' | 'retirement' | 'college' | 'vehicle' | 'renovation' | 'other';

export type PurchaseAdvisorRequest = {
    merchant?: string;
    item: string;
    description?: string;
    price: Money;
    source?: 'manual' | 'mobile_vision' | 'receipt' | 'product_photo';
    confidence?: number;
    user_question?: string;
};

export type RetirementScenarioRequest = {
    current_age: number;
    retirement_age: number;
    current_savings: Money;
    monthly_contribution: Money;
    annual_return_rate: number;
    annual_expenses?: Money;
};

export type Recommendation = {
    id: string;
    answer: string;
    assumptions: Array<string>;
    impacts: Array<Impact>;
    tradeoffs: Array<string>;
    alternatives: Array<string>;
    confidence: number;
    calculation_refs: Array<string>;
    warnings?: Array<string>;
    /**
     * Model id that produced the answer; null for deterministic answers
     */
    answered_by?: string;
    /**
     * Vision model that read an attached photo; null when none
     */
    photo_described_by?: string;
};

export type Impact = {
    area: 'cash_flow' | 'emergency_fund' | 'debt' | 'savings_goal' | 'retirement' | 'net_worth' | 'other';
    summary: string;
    amount?: Money;
};

export type ChatRequest = {
    conversation_id?: string;
    message: string;
    /**
     * Optional attached photo or PDF, base64-encoded (ADR 0011 / M84a)
     */
    image_base64?: string;
    image_media_type?: 'image/jpeg' | 'image/png' | 'image/webp' | 'application/pdf';
    /**
     * Optional attached data file (CSV / spreadsheet / text), base64. The server builds a bounded grounded preview for the prompt; the file is never stored (M85).
     */
    data_file_base64?: string;
    /**
     * Filename of the attached data file (drives format detection)
     */
    data_file_name?: string;
};

export type VoiceRequest = {
    text: string;
    /**
     * Optional voice id; defaults to the server's configured voice
     */
    voice?: string;
};

export type ChatResponse = {
    conversation_id: string;
    recommendation: Recommendation;
};

export type ImportCreateRequest = {
    source_type: ImportSourceType;
    filename: string;
    account_id?: string;
};

export type ImportRecord = {
    id: string;
    source_type: ImportSourceType;
    filename: string;
    status: 'pending' | 'processing' | 'needs_review' | 'completed' | 'discarded' | 'failed';
    error_message?: string;
    skipped_row_count?: number;
    created_at: string;
};

export type ImportListResponse = {
    imports: Array<ImportRecord>;
};

export type Document = {
    id: string;
    content_type: string;
    created_at: string;
    extraction?: DocumentExtraction;
};

export type DocumentExtraction = {
    id: string;
    extraction_type: 'pdf_text' | 'ocr';
    text: string;
    structured_fields: {
        [key: string]: unknown;
    };
    confidence: number;
    warnings: Array<string>;
    created_at: string;
};

export type DocumentListResponse = {
    documents: Array<Document>;
};

export type ImportSourceType = 'csv' | 'pdf' | 'ofx' | 'qfx';

export type ReportType = 'weekly' | 'monthly' | 'annual';

export type ExplanationSource = 'deterministic_stub' | 'llm';

export type GoalProgressSummary = {
    goal_id: string;
    name: string;
    percent_complete?: number;
    months_to_completion?: number;
    calculation_ref: string;
};

export type ReportSummary = {
    wins?: Array<string>;
    risks?: Array<string>;
    unusual_spending?: Array<string>;
    recommended_actions?: Array<string>;
    goal_progress?: Array<GoalProgressSummary>;
    net_cash_flow: Money;
    calculation_refs?: Array<string>;
};

export type Report = {
    id: string;
    report_type: ReportType;
    period_start: string;
    period_end: string;
    summary: ReportSummary;
    explanation_text: string;
    explanation_source: ExplanationSource;
    generated_at: string;
};

export type ReportListResponse = {
    reports: Array<Report>;
};

export type ReportGenerateRequest = {
    report_type: ReportType;
};

export type BackupJobStatus = 'pending' | 'running' | 'completed' | 'failed';

export type BackupJob = {
    id: string;
    status: BackupJobStatus;
    size_bytes?: number;
    error_message?: string;
    started_at: string;
    completed_at?: string;
    pruned_at?: string;
    created_at: string;
};

export type BackupJobListResponse = {
    backups: Array<BackupJob>;
};

export type HouseholdCreateRequest = {
    display_name: string;
    base_currency: string;
    owner_email: string;
    owner_password: string;
    owner_display_name: string;
};

/**
 * M43: household settings. Omit fields to leave them unchanged.
 */
export type HouseholdUpdateRequest = {
    /**
     * Months of expenses to target for the emergency fund (1-60).
     */
    emergency_fund_target_months?: number;
    /**
     * Reset the emergency-fund target to the default (6 months).
     */
    clear_emergency_fund_target?: boolean;
};

export type Member = {
    user_id: string;
    email: string;
    display_name: string;
    role: HouseholdRole;
    created_at: string;
};

export type MemberListResponse = {
    members: Array<Member>;
};

export type MemberCreateRequest = {
    email: string;
    password: string;
    display_name: string;
    role: HouseholdRole;
};

export type MemberRoleUpdateRequest = {
    role: HouseholdRole;
};

export type AccountCreateRequest = {
    name: string;
    type: AccountType;
    currency: string;
    annual_interest_rate?: number;
    minimum_payment?: Money;
};

export type AccountUpdateRequest = {
    name?: string;
    type?: AccountType;
    annual_interest_rate?: number;
    minimum_payment?: Money;
    /**
     * M36: reserve this percent of the balance for emergencies. Clears any fixed-amount designation. 400 if sent with emergency_fund_amount.
     */
    emergency_fund_percent?: number;
    /**
     * M36: reserve this fixed amount for emergencies. Clears any percent designation. 400 if sent with emergency_fund_percent.
     */
    emergency_fund_amount?: Money;
    /**
     * M36: remove the emergency-fund designation from this account.
     */
    clear_emergency_fund?: boolean;
};

export type AccountBalanceCreateRequest = {
    balance: Money;
};

export type TransactionCreateRequest = {
    account_id: string;
    occurred_at: string;
    amount: Money;
    merchant?: string;
    description?: string;
    /**
     * M45: assign a spending category.
     */
    category_id?: string;
};

export type TransactionUpdateRequest = {
    account_id?: string;
    occurred_at?: string;
    amount?: Money;
    merchant?: string;
    description?: string;
    /**
     * M45: assign a spending category.
     */
    category_id?: string;
    /**
     * M45: remove the category from this transaction.
     */
    clear_category?: boolean;
};

export type BillCreateRequest = {
    name: string;
    amount: Money;
    frequency: RecurringFrequency;
    account_id?: string;
    next_due_date?: string;
};

export type BillUpdateRequest = {
    name?: string;
    amount?: Money;
    frequency?: RecurringFrequency;
    next_due_date?: string;
};

export type IncomeCreateRequest = {
    name: string;
    amount: Money;
    frequency: RecurringFrequency;
};

export type IncomeUpdateRequest = {
    name?: string;
    amount?: Money;
    frequency?: RecurringFrequency;
};

export type AuditEvent = {
    id: string;
    actor_user_id?: string;
    action: string;
    entity_type: string;
    entity_id?: string;
    summary: string;
    created_at: string;
};

export type AuditEventListResponse = {
    events: Array<AuditEvent>;
};

export type Conversation = {
    id: string;
    title: string;
    created_at: string;
    updated_at: string;
    message_count?: number;
};

export type ConversationListResponse = {
    conversations: Array<Conversation>;
};

export type ConversationMessage = {
    id: string;
    role: 'user' | 'assistant';
    content: string;
    recommendation_id?: string;
    sequence: number;
    created_at: string;
};

export type ConversationDetail = {
    id: string;
    title: string;
    created_at: string;
    updated_at: string;
    messages: Array<ConversationMessage>;
};

export type AiRuntimeConfig = {
    provider: 'vllm' | 'ollama' | 'llama_cpp' | 'openai_compatible';
    base_url: string;
    model: string;
    enabled?: boolean;
};

export type AiRuntimeStatus = {
    enabled: boolean;
    provider: string;
    model: string;
    ready: boolean;
    served_model?: string;
    detail: string;
    vision_ready?: boolean;
    vision_model?: string;
    vision_enabled?: boolean;
    /**
     * M50: what 'loading' actually means, classified from the vLLM log tail.
     */
    loading_phase?: 'downloading' | 'loading' | 'warming_up' | 'error' | 'starting';
    /**
     * Human detail (download %, shard %, or the crash line).
     */
    loading_detail?: string;
};

export type AiModelInfo = {
    id: string;
    label: string;
    role: 'main' | 'vision' | 'both';
    parameters_b: number;
    est_memory_gb: number;
    est_disk_gb: number;
    tool_parser?: string;
    supports_vision: boolean;
    /**
     * Hugging Face release timestamp (M71); absent for curated entries, which the picker treats as modern (hand-vetted).
     *
     */
    created_at?: string;
    gated: boolean;
    notes?: string;
};

export type AiModelCatalog = {
    models: Array<AiModelInfo>;
};

export type ConnectionCreateRequest = {
    provider?: 'simplefin';
    display_name: string;
    setup_token: string;
};

export type InstitutionConnection = {
    id: string;
    provider: string;
    display_name: string;
    status: string;
    last_synced_at?: string;
    last_sync_error?: string;
    created_at: string;
};

export type ConnectionListResponse = {
    connections: Array<InstitutionConnection>;
};

export type ConnectionSyncResult = {
    accounts_synced: number;
    imported: number;
    duplicates_skipped: number;
};

export type AiApplyRequest = {
    main_model: string;
    vision_model?: string;
};

export type AiSwapStatus = {
    state: 'idle' | 'running' | 'succeeded' | 'failed' | 'unavailable';
    main_model?: string;
    vision_model?: string;
    log_tail?: string;
};

export type AiHardwareProfile = {
    gpu_memory_gb?: number;
    system_memory_gb?: number;
    disk_free_gb: number;
    source: string;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Service health
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type CreatePairingSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pairing/sessions';
};

export type CreatePairingSessionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreatePairingSessionError = CreatePairingSessionErrors[keyof CreatePairingSessionErrors];

export type CreatePairingSessionResponses = {
    /**
     * Pairing session created
     */
    201: PairingSession;
};

export type CreatePairingSessionResponse = CreatePairingSessionResponses[keyof CreatePairingSessionResponses];

export type ConfirmPairingData = {
    body: PairingConfirmRequest;
    path?: never;
    query?: never;
    url: '/pairing/confirm';
};

export type ConfirmPairingErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
};

export type ConfirmPairingError = ConfirmPairingErrors[keyof ConfirmPairingErrors];

export type ConfirmPairingResponses = {
    /**
     * Device paired
     */
    200: DeviceCredential;
};

export type ConfirmPairingResponse = ConfirmPairingResponses[keyof ConfirmPairingResponses];

export type ListPairedDevicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pairing/devices';
};

export type ListPairedDevicesErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListPairedDevicesError = ListPairedDevicesErrors[keyof ListPairedDevicesErrors];

export type ListPairedDevicesResponses = {
    /**
     * Paired devices
     */
    200: PairedDeviceListResponse;
};

export type ListPairedDevicesResponse = ListPairedDevicesResponses[keyof ListPairedDevicesResponses];

export type RevokePairedDeviceData = {
    body?: never;
    path: {
        device_id: string;
    };
    query?: never;
    url: '/pairing/devices/{device_id}';
};

export type RevokePairedDeviceErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type RevokePairedDeviceError = RevokePairedDeviceErrors[keyof RevokePairedDeviceErrors];

export type RevokePairedDeviceResponses = {
    /**
     * Paired device revoked
     */
    204: void;
};

export type RevokePairedDeviceResponse = RevokePairedDeviceResponses[keyof RevokePairedDeviceResponses];

export type DeleteAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sessions';
};

export type DeleteAuthSessionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type DeleteAuthSessionError = DeleteAuthSessionErrors[keyof DeleteAuthSessionErrors];

export type DeleteAuthSessionResponses = {
    /**
     * Session revoked
     */
    204: void;
};

export type DeleteAuthSessionResponse = DeleteAuthSessionResponses[keyof DeleteAuthSessionResponses];

export type CreateAuthSessionData = {
    body: AuthSessionCreateRequest;
    path?: never;
    query?: never;
    url: '/auth/sessions';
};

export type CreateAuthSessionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type CreateAuthSessionError = CreateAuthSessionErrors[keyof CreateAuthSessionErrors];

export type CreateAuthSessionResponses = {
    /**
     * Authentication session created
     */
    201: AuthSession;
};

export type CreateAuthSessionResponse = CreateAuthSessionResponses[keyof CreateAuthSessionResponses];

export type RefreshAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sessions/refresh';
};

export type RefreshAuthSessionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type RefreshAuthSessionError = RefreshAuthSessionErrors[keyof RefreshAuthSessionErrors];

export type RefreshAuthSessionResponses = {
    /**
     * New session issued; the old token is now invalid
     */
    200: AuthSession;
};

export type RefreshAuthSessionResponse = RefreshAuthSessionResponses[keyof RefreshAuthSessionResponses];

export type CreateHouseholdData = {
    body: HouseholdCreateRequest;
    path?: never;
    query?: never;
    url: '/households';
};

export type CreateHouseholdErrors = {
    /**
     * Error response
     */
    409: ErrorResponse;
};

export type CreateHouseholdError = CreateHouseholdErrors[keyof CreateHouseholdErrors];

export type CreateHouseholdResponses = {
    /**
     * Household created; returns an authenticated session for the new owner
     */
    201: AuthSession;
};

export type CreateHouseholdResponse = CreateHouseholdResponses[keyof CreateHouseholdResponses];

export type GetHouseholdContextData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/household';
};

export type GetHouseholdContextErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type GetHouseholdContextError = GetHouseholdContextErrors[keyof GetHouseholdContextErrors];

export type GetHouseholdContextResponses = {
    /**
     * Household context
     */
    200: HouseholdContext;
};

export type GetHouseholdContextResponse = GetHouseholdContextResponses[keyof GetHouseholdContextResponses];

export type UpdateHouseholdData = {
    body: HouseholdUpdateRequest;
    path?: never;
    query?: never;
    url: '/household';
};

export type UpdateHouseholdErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type UpdateHouseholdError = UpdateHouseholdErrors[keyof UpdateHouseholdErrors];

export type UpdateHouseholdResponses = {
    /**
     * Updated household context
     */
    200: HouseholdContext;
};

export type UpdateHouseholdResponse = UpdateHouseholdResponses[keyof UpdateHouseholdResponses];

export type ListMembersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/household/members';
};

export type ListMembersErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListMembersError = ListMembersErrors[keyof ListMembersErrors];

export type ListMembersResponses = {
    /**
     * Household members
     */
    200: MemberListResponse;
};

export type ListMembersResponse = ListMembersResponses[keyof ListMembersResponses];

export type CreateMemberData = {
    body: MemberCreateRequest;
    path?: never;
    query?: never;
    url: '/household/members';
};

export type CreateMemberErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    409: ErrorResponse;
};

export type CreateMemberError = CreateMemberErrors[keyof CreateMemberErrors];

export type CreateMemberResponses = {
    /**
     * Member added
     */
    201: Member;
};

export type CreateMemberResponse = CreateMemberResponses[keyof CreateMemberResponses];

export type DeleteMemberData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/household/members/{user_id}';
};

export type DeleteMemberErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
    /**
     * Error response
     */
    409: ErrorResponse;
};

export type DeleteMemberError = DeleteMemberErrors[keyof DeleteMemberErrors];

export type DeleteMemberResponses = {
    /**
     * Member removed
     */
    204: void;
};

export type DeleteMemberResponse = DeleteMemberResponses[keyof DeleteMemberResponses];

export type UpdateMemberRoleData = {
    body: MemberRoleUpdateRequest;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/household/members/{user_id}';
};

export type UpdateMemberRoleErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
    /**
     * Error response
     */
    409: ErrorResponse;
};

export type UpdateMemberRoleError = UpdateMemberRoleErrors[keyof UpdateMemberRoleErrors];

export type UpdateMemberRoleResponses = {
    /**
     * Member role changed
     */
    200: Member;
};

export type UpdateMemberRoleResponse = UpdateMemberRoleResponses[keyof UpdateMemberRoleResponses];

export type ListAuditEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/audit';
};

export type ListAuditEventsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type ListAuditEventsError = ListAuditEventsErrors[keyof ListAuditEventsErrors];

export type ListAuditEventsResponses = {
    /**
     * Audit events
     */
    200: AuditEventListResponse;
};

export type ListAuditEventsResponse = ListAuditEventsResponses[keyof ListAuditEventsResponses];

export type ListAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/accounts';
};

export type ListAccountsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListAccountsError = ListAccountsErrors[keyof ListAccountsErrors];

export type ListAccountsResponses = {
    /**
     * Accounts
     */
    200: AccountListResponse;
};

export type ListAccountsResponse = ListAccountsResponses[keyof ListAccountsResponses];

export type CreateAccountData = {
    body: AccountCreateRequest;
    path?: never;
    query?: never;
    url: '/accounts';
};

export type CreateAccountErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreateAccountError = CreateAccountErrors[keyof CreateAccountErrors];

export type CreateAccountResponses = {
    /**
     * Account created
     */
    201: Account;
};

export type CreateAccountResponse = CreateAccountResponses[keyof CreateAccountResponses];

export type DeleteAccountData = {
    body?: never;
    path: {
        account_id: string;
    };
    query?: never;
    url: '/accounts/{account_id}';
};

export type DeleteAccountErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
    /**
     * Error response
     */
    409: ErrorResponse;
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
    /**
     * Account deleted
     */
    204: void;
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type UpdateAccountData = {
    body: AccountUpdateRequest;
    path: {
        account_id: string;
    };
    query?: never;
    url: '/accounts/{account_id}';
};

export type UpdateAccountErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type UpdateAccountError = UpdateAccountErrors[keyof UpdateAccountErrors];

export type UpdateAccountResponses = {
    /**
     * Account updated
     */
    200: Account;
};

export type UpdateAccountResponse = UpdateAccountResponses[keyof UpdateAccountResponses];

export type RecordAccountBalanceData = {
    body: AccountBalanceCreateRequest;
    path: {
        account_id: string;
    };
    query?: never;
    url: '/accounts/{account_id}/balances';
};

export type RecordAccountBalanceErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type RecordAccountBalanceError = RecordAccountBalanceErrors[keyof RecordAccountBalanceErrors];

export type RecordAccountBalanceResponses = {
    /**
     * Balance recorded
     */
    201: Account;
};

export type RecordAccountBalanceResponse = RecordAccountBalanceResponses[keyof RecordAccountBalanceResponses];

export type ListTransactionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/transactions';
};

export type ListTransactionsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListTransactionsError = ListTransactionsErrors[keyof ListTransactionsErrors];

export type ListTransactionsResponses = {
    /**
     * Transactions
     */
    200: TransactionListResponse;
};

export type ListTransactionsResponse = ListTransactionsResponses[keyof ListTransactionsResponses];

export type CreateTransactionData = {
    body: TransactionCreateRequest;
    path?: never;
    query?: never;
    url: '/transactions';
};

export type CreateTransactionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type CreateTransactionError = CreateTransactionErrors[keyof CreateTransactionErrors];

export type CreateTransactionResponses = {
    /**
     * Transaction created
     */
    201: Transaction;
};

export type CreateTransactionResponse = CreateTransactionResponses[keyof CreateTransactionResponses];

export type DeleteTransactionData = {
    body?: never;
    path: {
        transaction_id: string;
    };
    query?: never;
    url: '/transactions/{transaction_id}';
};

export type DeleteTransactionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DeleteTransactionError = DeleteTransactionErrors[keyof DeleteTransactionErrors];

export type DeleteTransactionResponses = {
    /**
     * Transaction deleted
     */
    204: void;
};

export type DeleteTransactionResponse = DeleteTransactionResponses[keyof DeleteTransactionResponses];

export type UpdateTransactionData = {
    body: TransactionUpdateRequest;
    path: {
        transaction_id: string;
    };
    query?: never;
    url: '/transactions/{transaction_id}';
};

export type UpdateTransactionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type UpdateTransactionError = UpdateTransactionErrors[keyof UpdateTransactionErrors];

export type UpdateTransactionResponses = {
    /**
     * Transaction updated
     */
    200: Transaction;
};

export type UpdateTransactionResponse = UpdateTransactionResponses[keyof UpdateTransactionResponses];

export type ListCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories';
};

export type ListCategoriesErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListCategoriesError = ListCategoriesErrors[keyof ListCategoriesErrors];

export type ListCategoriesResponses = {
    /**
     * Categories
     */
    200: CategoryListResponse;
};

export type ListCategoriesResponse = ListCategoriesResponses[keyof ListCategoriesResponses];

export type CreateCategoryData = {
    body: CategoryCreateRequest;
    path?: never;
    query?: never;
    url: '/categories';
};

export type CreateCategoryErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    409: ErrorResponse;
};

export type CreateCategoryError = CreateCategoryErrors[keyof CreateCategoryErrors];

export type CreateCategoryResponses = {
    /**
     * Category created
     */
    201: Category;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type DeleteCategoryData = {
    body?: never;
    path: {
        category_id: string;
    };
    query?: never;
    url: '/categories/{category_id}';
};

export type DeleteCategoryErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DeleteCategoryError = DeleteCategoryErrors[keyof DeleteCategoryErrors];

export type DeleteCategoryResponses = {
    /**
     * Category deleted
     */
    204: void;
};

export type DeleteCategoryResponse = DeleteCategoryResponses[keyof DeleteCategoryResponses];

export type ListBudgetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/budgets';
};

export type ListBudgetsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListBudgetsError = ListBudgetsErrors[keyof ListBudgetsErrors];

export type ListBudgetsResponses = {
    /**
     * Budgets
     */
    200: BudgetListResponse;
};

export type ListBudgetsResponse = ListBudgetsResponses[keyof ListBudgetsResponses];

export type CreateBudgetData = {
    body: BudgetCreateRequest;
    path?: never;
    query?: never;
    url: '/budgets';
};

export type CreateBudgetErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
    /**
     * Error response
     */
    409: ErrorResponse;
};

export type CreateBudgetError = CreateBudgetErrors[keyof CreateBudgetErrors];

export type CreateBudgetResponses = {
    /**
     * Budget created
     */
    201: Budget;
};

export type CreateBudgetResponse = CreateBudgetResponses[keyof CreateBudgetResponses];

export type DeleteBudgetData = {
    body?: never;
    path: {
        budget_id: string;
    };
    query?: never;
    url: '/budgets/{budget_id}';
};

export type DeleteBudgetErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DeleteBudgetError = DeleteBudgetErrors[keyof DeleteBudgetErrors];

export type DeleteBudgetResponses = {
    /**
     * Budget deleted
     */
    204: void;
};

export type DeleteBudgetResponse = DeleteBudgetResponses[keyof DeleteBudgetResponses];

export type UpdateBudgetData = {
    body: BudgetUpdateRequest;
    path: {
        budget_id: string;
    };
    query?: never;
    url: '/budgets/{budget_id}';
};

export type UpdateBudgetErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type UpdateBudgetError = UpdateBudgetErrors[keyof UpdateBudgetErrors];

export type UpdateBudgetResponses = {
    /**
     * Budget updated
     */
    200: Budget;
};

export type UpdateBudgetResponse = UpdateBudgetResponses[keyof UpdateBudgetResponses];

export type ListBillsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/bills';
};

export type ListBillsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListBillsError = ListBillsErrors[keyof ListBillsErrors];

export type ListBillsResponses = {
    /**
     * Bills
     */
    200: BillListResponse;
};

export type ListBillsResponse = ListBillsResponses[keyof ListBillsResponses];

export type CreateBillData = {
    body: BillCreateRequest;
    path?: never;
    query?: never;
    url: '/bills';
};

export type CreateBillErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreateBillError = CreateBillErrors[keyof CreateBillErrors];

export type CreateBillResponses = {
    /**
     * Bill created
     */
    201: Bill;
};

export type CreateBillResponse = CreateBillResponses[keyof CreateBillResponses];

export type ListBillSuggestionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/bills/suggestions';
};

export type ListBillSuggestionsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListBillSuggestionsError = ListBillSuggestionsErrors[keyof ListBillSuggestionsErrors];

export type ListBillSuggestionsResponses = {
    /**
     * Suggested bills
     */
    200: BillSuggestionListResponse;
};

export type ListBillSuggestionsResponse = ListBillSuggestionsResponses[keyof ListBillSuggestionsResponses];

export type DismissBillSuggestionData = {
    body: BillSuggestionDismissRequest;
    path?: never;
    query?: never;
    url: '/bills/suggestions/dismissals';
};

export type DismissBillSuggestionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type DismissBillSuggestionError = DismissBillSuggestionErrors[keyof DismissBillSuggestionErrors];

export type DismissBillSuggestionResponses = {
    /**
     * Suggestion dismissed
     */
    204: void;
};

export type DismissBillSuggestionResponse = DismissBillSuggestionResponses[keyof DismissBillSuggestionResponses];

export type DeleteBillData = {
    body?: never;
    path: {
        bill_id: string;
    };
    query?: never;
    url: '/bills/{bill_id}';
};

export type DeleteBillErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DeleteBillError = DeleteBillErrors[keyof DeleteBillErrors];

export type DeleteBillResponses = {
    /**
     * Bill deleted
     */
    204: void;
};

export type DeleteBillResponse = DeleteBillResponses[keyof DeleteBillResponses];

export type UpdateBillData = {
    body: BillUpdateRequest;
    path: {
        bill_id: string;
    };
    query?: never;
    url: '/bills/{bill_id}';
};

export type UpdateBillErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type UpdateBillError = UpdateBillErrors[keyof UpdateBillErrors];

export type UpdateBillResponses = {
    /**
     * Bill updated
     */
    200: Bill;
};

export type UpdateBillResponse = UpdateBillResponses[keyof UpdateBillResponses];

export type ListIncomeSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/income';
};

export type ListIncomeSourcesErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListIncomeSourcesError = ListIncomeSourcesErrors[keyof ListIncomeSourcesErrors];

export type ListIncomeSourcesResponses = {
    /**
     * Income sources
     */
    200: IncomeListResponse;
};

export type ListIncomeSourcesResponse = ListIncomeSourcesResponses[keyof ListIncomeSourcesResponses];

export type CreateIncomeSourceData = {
    body: IncomeCreateRequest;
    path?: never;
    query?: never;
    url: '/income';
};

export type CreateIncomeSourceErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreateIncomeSourceError = CreateIncomeSourceErrors[keyof CreateIncomeSourceErrors];

export type CreateIncomeSourceResponses = {
    /**
     * Income source created
     */
    201: IncomeSource;
};

export type CreateIncomeSourceResponse = CreateIncomeSourceResponses[keyof CreateIncomeSourceResponses];

export type DeleteIncomeSourceData = {
    body?: never;
    path: {
        income_id: string;
    };
    query?: never;
    url: '/income/{income_id}';
};

export type DeleteIncomeSourceErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DeleteIncomeSourceError = DeleteIncomeSourceErrors[keyof DeleteIncomeSourceErrors];

export type DeleteIncomeSourceResponses = {
    /**
     * Income source deleted
     */
    204: void;
};

export type DeleteIncomeSourceResponse = DeleteIncomeSourceResponses[keyof DeleteIncomeSourceResponses];

export type UpdateIncomeSourceData = {
    body: IncomeUpdateRequest;
    path: {
        income_id: string;
    };
    query?: never;
    url: '/income/{income_id}';
};

export type UpdateIncomeSourceErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type UpdateIncomeSourceError = UpdateIncomeSourceErrors[keyof UpdateIncomeSourceErrors];

export type UpdateIncomeSourceResponses = {
    /**
     * Income source updated
     */
    200: IncomeSource;
};

export type UpdateIncomeSourceResponse = UpdateIncomeSourceResponses[keyof UpdateIncomeSourceResponses];

export type GetIncomeAnalysisData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/income/analysis';
};

export type GetIncomeAnalysisErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type GetIncomeAnalysisError = GetIncomeAnalysisErrors[keyof GetIncomeAnalysisErrors];

export type GetIncomeAnalysisResponses = {
    /**
     * Income analysis with evidence transactions and tax estimate
     */
    200: IncomeAnalysisResponse;
};

export type GetIncomeAnalysisResponse = GetIncomeAnalysisResponses[keyof GetIncomeAnalysisResponses];

export type SetIncomeOverrideData = {
    body: IncomeOverrideRequest;
    path?: never;
    query?: never;
    url: '/income/analysis/overrides';
};

export type SetIncomeOverrideErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type SetIncomeOverrideError = SetIncomeOverrideErrors[keyof SetIncomeOverrideErrors];

export type SetIncomeOverrideResponses = {
    /**
     * Override stored
     */
    204: void;
};

export type SetIncomeOverrideResponse = SetIncomeOverrideResponses[keyof SetIncomeOverrideResponses];

export type UpdateIncomeTaxSettingsData = {
    body: IncomeTaxSettingsRequest;
    path?: never;
    query?: never;
    url: '/income/analysis/settings';
};

export type UpdateIncomeTaxSettingsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type UpdateIncomeTaxSettingsError = UpdateIncomeTaxSettingsErrors[keyof UpdateIncomeTaxSettingsErrors];

export type UpdateIncomeTaxSettingsResponses = {
    /**
     * Settings stored
     */
    204: void;
};

export type UpdateIncomeTaxSettingsResponse = UpdateIncomeTaxSettingsResponses[keyof UpdateIncomeTaxSettingsResponses];

export type CreateIncomeEarnerData = {
    body: IncomeEarnerCreateRequest;
    path?: never;
    query?: never;
    url: '/income/profile/earners';
};

export type CreateIncomeEarnerErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreateIncomeEarnerError = CreateIncomeEarnerErrors[keyof CreateIncomeEarnerErrors];

export type CreateIncomeEarnerResponses = {
    /**
     * Earner declared
     */
    201: IncomeEarner;
};

export type CreateIncomeEarnerResponse = CreateIncomeEarnerResponses[keyof CreateIncomeEarnerResponses];

export type DeleteIncomeEarnerData = {
    body?: never;
    path: {
        earner_id: string;
    };
    query?: never;
    url: '/income/profile/earners/{earner_id}';
};

export type DeleteIncomeEarnerErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DeleteIncomeEarnerError = DeleteIncomeEarnerErrors[keyof DeleteIncomeEarnerErrors];

export type DeleteIncomeEarnerResponses = {
    /**
     * Earner removed
     */
    204: void;
};

export type DeleteIncomeEarnerResponse = DeleteIncomeEarnerResponses[keyof DeleteIncomeEarnerResponses];

export type ScanW2Data = {
    body: W2ScanRequest;
    path?: never;
    query?: never;
    url: '/income/profile/scan-w2';
};

export type ScanW2Errors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    422: ErrorResponse;
    /**
     * Error response
     */
    503: ErrorResponse;
};

export type ScanW2Error = ScanW2Errors[keyof ScanW2Errors];

export type ScanW2Responses = {
    /**
     * Candidate values extracted by the on-box vision model
     */
    200: W2ScanResult;
};

export type ScanW2Response = ScanW2Responses[keyof ScanW2Responses];

export type ListGoalsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/goals';
};

export type ListGoalsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListGoalsError = ListGoalsErrors[keyof ListGoalsErrors];

export type ListGoalsResponses = {
    /**
     * Goals
     */
    200: GoalListResponse;
};

export type ListGoalsResponse = ListGoalsResponses[keyof ListGoalsResponses];

export type CreateGoalData = {
    body: GoalCreateRequest;
    path?: never;
    query?: never;
    url: '/goals';
};

export type CreateGoalErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreateGoalError = CreateGoalErrors[keyof CreateGoalErrors];

export type CreateGoalResponses = {
    /**
     * Goal created
     */
    201: Goal;
};

export type CreateGoalResponse = CreateGoalResponses[keyof CreateGoalResponses];

export type AnalyzePurchaseData = {
    body: PurchaseAdvisorRequest;
    path?: never;
    query?: never;
    url: '/advisor/purchase';
};

export type AnalyzePurchaseErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type AnalyzePurchaseError = AnalyzePurchaseErrors[keyof AnalyzePurchaseErrors];

export type AnalyzePurchaseResponses = {
    /**
     * Purchase recommendation
     */
    200: Recommendation;
};

export type AnalyzePurchaseResponse = AnalyzePurchaseResponses[keyof AnalyzePurchaseResponses];

export type AnalyzeRetirementData = {
    body: RetirementScenarioRequest;
    path?: never;
    query?: never;
    url: '/advisor/retirement';
};

export type AnalyzeRetirementErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type AnalyzeRetirementError = AnalyzeRetirementErrors[keyof AnalyzeRetirementErrors];

export type AnalyzeRetirementResponses = {
    /**
     * Retirement projection recommendation
     */
    200: Recommendation;
};

export type AnalyzeRetirementResponse = AnalyzeRetirementResponses[keyof AnalyzeRetirementResponses];

export type CreateChatMessageData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/chat/messages';
};

export type CreateChatMessageErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type CreateChatMessageError = CreateChatMessageErrors[keyof CreateChatMessageErrors];

export type CreateChatMessageResponses = {
    /**
     * Chat response
     */
    200: ChatResponse;
};

export type CreateChatMessageResponse = CreateChatMessageResponses[keyof CreateChatMessageResponses];

export type SynthesizeSpeechData = {
    body: VoiceRequest;
    path?: never;
    query?: never;
    url: '/voice/tts';
};

export type SynthesizeSpeechErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    503: ErrorResponse;
};

export type SynthesizeSpeechError = SynthesizeSpeechErrors[keyof SynthesizeSpeechErrors];

export type SynthesizeSpeechResponses = {
    /**
     * Synthesized speech
     */
    200: Blob | File;
};

export type SynthesizeSpeechResponse = SynthesizeSpeechResponses[keyof SynthesizeSpeechResponses];

export type ListMemoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/memories';
};

export type ListMemoriesErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListMemoriesError = ListMemoriesErrors[keyof ListMemoriesErrors];

export type ListMemoriesResponses = {
    /**
     * Remembered household facts
     */
    200: MemoryListResponse;
};

export type ListMemoriesResponse = ListMemoriesResponses[keyof ListMemoriesResponses];

export type CreateMemoryData = {
    body: MemoryCreateRequest;
    path?: never;
    query?: never;
    url: '/memories';
};

export type CreateMemoryErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreateMemoryError = CreateMemoryErrors[keyof CreateMemoryErrors];

export type CreateMemoryResponses = {
    /**
     * Memory stored
     */
    201: Memory;
};

export type CreateMemoryResponse = CreateMemoryResponses[keyof CreateMemoryResponses];

export type DeleteMemoryData = {
    body?: never;
    path: {
        memory_id: string;
    };
    query?: never;
    url: '/memories/{memory_id}';
};

export type DeleteMemoryErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DeleteMemoryError = DeleteMemoryErrors[keyof DeleteMemoryErrors];

export type DeleteMemoryResponses = {
    /**
     * Memory deleted
     */
    204: void;
};

export type DeleteMemoryResponse = DeleteMemoryResponses[keyof DeleteMemoryResponses];

export type ListConversationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/conversations';
};

export type ListConversationsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListConversationsError = ListConversationsErrors[keyof ListConversationsErrors];

export type ListConversationsResponses = {
    /**
     * Conversations
     */
    200: ConversationListResponse;
};

export type ListConversationsResponse = ListConversationsResponses[keyof ListConversationsResponses];

export type DeleteConversationData = {
    body?: never;
    path: {
        conversation_id: string;
    };
    query?: never;
    url: '/conversations/{conversation_id}';
};

export type DeleteConversationErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DeleteConversationError = DeleteConversationErrors[keyof DeleteConversationErrors];

export type DeleteConversationResponses = {
    /**
     * Conversation deleted
     */
    204: void;
};

export type DeleteConversationResponse = DeleteConversationResponses[keyof DeleteConversationResponses];

export type GetConversationData = {
    body?: never;
    path: {
        conversation_id: string;
    };
    query?: never;
    url: '/conversations/{conversation_id}';
};

export type GetConversationErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type GetConversationError = GetConversationErrors[keyof GetConversationErrors];

export type GetConversationResponses = {
    /**
     * Conversation detail
     */
    200: ConversationDetail;
};

export type GetConversationResponse = GetConversationResponses[keyof GetConversationResponses];

export type ListImportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/imports';
};

export type ListImportsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListImportsError = ListImportsErrors[keyof ListImportsErrors];

export type ListImportsResponses = {
    /**
     * Import jobs
     */
    200: ImportListResponse;
};

export type ListImportsResponse = ListImportsResponses[keyof ListImportsResponses];

export type CreateImportData = {
    body: ImportCreateRequest;
    path?: never;
    query?: never;
    url: '/imports';
};

export type CreateImportErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type CreateImportError = CreateImportErrors[keyof CreateImportErrors];

export type CreateImportResponses = {
    /**
     * Import registered
     */
    201: ImportRecord;
};

export type CreateImportResponse = CreateImportResponses[keyof CreateImportResponses];

export type UploadImportFileData = {
    body: {
        file: Blob | File;
    };
    path: {
        import_id: string;
    };
    query?: never;
    url: '/imports/{import_id}/file';
};

export type UploadImportFileErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type UploadImportFileError = UploadImportFileErrors[keyof UploadImportFileErrors];

export type UploadImportFileResponses = {
    /**
     * File staged for background processing
     */
    202: ImportRecord;
};

export type UploadImportFileResponse = UploadImportFileResponses[keyof UploadImportFileResponses];

export type ApplyImportData = {
    body?: never;
    path: {
        import_id: string;
    };
    query?: never;
    url: '/imports/{import_id}/apply';
};

export type ApplyImportErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type ApplyImportError = ApplyImportErrors[keyof ApplyImportErrors];

export type ApplyImportResponses = {
    /**
     * Import applied
     */
    200: ImportRecord;
};

export type ApplyImportResponse = ApplyImportResponses[keyof ApplyImportResponses];

export type DiscardImportData = {
    body?: never;
    path: {
        import_id: string;
    };
    query?: never;
    url: '/imports/{import_id}/discard';
};

export type DiscardImportErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DiscardImportError = DiscardImportErrors[keyof DiscardImportErrors];

export type DiscardImportResponses = {
    /**
     * Import discarded
     */
    200: ImportRecord;
};

export type DiscardImportResponse = DiscardImportResponses[keyof DiscardImportResponses];

export type ListDocumentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/documents';
};

export type ListDocumentsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListDocumentsError = ListDocumentsErrors[keyof ListDocumentsErrors];

export type ListDocumentsResponses = {
    /**
     * Documents
     */
    200: DocumentListResponse;
};

export type ListDocumentsResponse = ListDocumentsResponses[keyof ListDocumentsResponses];

export type CreateDocumentData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/documents';
};

export type CreateDocumentErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type CreateDocumentError = CreateDocumentErrors[keyof CreateDocumentErrors];

export type CreateDocumentResponses = {
    /**
     * Document created and extracted
     */
    201: Document;
};

export type CreateDocumentResponse = CreateDocumentResponses[keyof CreateDocumentResponses];

export type ListReportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reports';
};

export type ListReportsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListReportsError = ListReportsErrors[keyof ListReportsErrors];

export type ListReportsResponses = {
    /**
     * Reports
     */
    200: ReportListResponse;
};

export type ListReportsResponse = ListReportsResponses[keyof ListReportsResponses];

export type GetReportData = {
    body?: never;
    path: {
        report_id: string;
    };
    query?: never;
    url: '/reports/{report_id}';
};

export type GetReportErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type GetReportError = GetReportErrors[keyof GetReportErrors];

export type GetReportResponses = {
    /**
     * Report
     */
    200: Report;
};

export type GetReportResponse = GetReportResponses[keyof GetReportResponses];

export type GenerateReportData = {
    body: ReportGenerateRequest;
    path?: never;
    query?: never;
    url: '/reports/generate';
};

export type GenerateReportErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type GenerateReportError = GenerateReportErrors[keyof GenerateReportErrors];

export type GenerateReportResponses = {
    /**
     * Report generated
     */
    201: Report;
};

export type GenerateReportResponse = GenerateReportResponses[keyof GenerateReportResponses];

export type ListBackupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/backups';
};

export type ListBackupsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type ListBackupsError = ListBackupsErrors[keyof ListBackupsErrors];

export type ListBackupsResponses = {
    /**
     * Backup jobs
     */
    200: BackupJobListResponse;
};

export type ListBackupsResponse = ListBackupsResponses[keyof ListBackupsResponses];

export type CreateBackupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/backups';
};

export type CreateBackupErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type CreateBackupError = CreateBackupErrors[keyof CreateBackupErrors];

export type CreateBackupResponses = {
    /**
     * Backup created
     */
    201: BackupJob;
};

export type CreateBackupResponse = CreateBackupResponses[keyof CreateBackupResponses];

export type RestoreBackupData = {
    body?: never;
    path: {
        backup_id: string;
    };
    query?: never;
    url: '/backups/{backup_id}/restore';
};

export type RestoreBackupErrors = {
    /**
     * Error response
     */
    400: ErrorResponse;
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type RestoreBackupError = RestoreBackupErrors[keyof RestoreBackupErrors];

export type RestoreBackupResponses = {
    /**
     * Backup restored
     */
    200: BackupJob;
};

export type RestoreBackupResponse = RestoreBackupResponses[keyof RestoreBackupResponses];

export type GetAiRuntimeConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ai/runtime';
};

export type GetAiRuntimeConfigErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type GetAiRuntimeConfigError = GetAiRuntimeConfigErrors[keyof GetAiRuntimeConfigErrors];

export type GetAiRuntimeConfigResponses = {
    /**
     * AI runtime configuration
     */
    200: AiRuntimeConfig;
};

export type GetAiRuntimeConfigResponse = GetAiRuntimeConfigResponses[keyof GetAiRuntimeConfigResponses];

export type UpdateAiRuntimeConfigData = {
    body: AiRuntimeConfig;
    path?: never;
    query?: never;
    url: '/ai/runtime';
};

export type UpdateAiRuntimeConfigErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
};

export type UpdateAiRuntimeConfigError = UpdateAiRuntimeConfigErrors[keyof UpdateAiRuntimeConfigErrors];

export type UpdateAiRuntimeConfigResponses = {
    /**
     * AI runtime configuration
     */
    200: AiRuntimeConfig;
};

export type UpdateAiRuntimeConfigResponse = UpdateAiRuntimeConfigResponses[keyof UpdateAiRuntimeConfigResponses];

export type GetAiRuntimeStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ai/runtime/status';
};

export type GetAiRuntimeStatusErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type GetAiRuntimeStatusError = GetAiRuntimeStatusErrors[keyof GetAiRuntimeStatusErrors];

export type GetAiRuntimeStatusResponses = {
    /**
     * AI runtime status
     */
    200: AiRuntimeStatus;
};

export type GetAiRuntimeStatusResponse = GetAiRuntimeStatusResponses[keyof GetAiRuntimeStatusResponses];

export type ListAiModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ai/models';
};

export type ListAiModelsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListAiModelsError = ListAiModelsErrors[keyof ListAiModelsErrors];

export type ListAiModelsResponses = {
    /**
     * Curated model catalog
     */
    200: AiModelCatalog;
};

export type ListAiModelsResponse = ListAiModelsResponses[keyof ListAiModelsResponses];

export type GetAiHardwareProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ai/hardware';
};

export type GetAiHardwareProfileErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type GetAiHardwareProfileError = GetAiHardwareProfileErrors[keyof GetAiHardwareProfileErrors];

export type GetAiHardwareProfileResponses = {
    /**
     * Hardware profile
     */
    200: AiHardwareProfile;
};

export type GetAiHardwareProfileResponse = GetAiHardwareProfileResponses[keyof GetAiHardwareProfileResponses];

export type SearchAiModelsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Empty returns the pipeline's most-downloaded models (M48 live quick-filter lists).
         */
        q?: string;
        pipeline?: 'any' | 'text-generation' | 'image-text-to-text';
        limit?: number;
        /**
         * M53: fan out size/quant-hinted queries so the largest fitting models surface.
         */
        deep?: boolean;
    };
    url: '/ai/models/search';
};

export type SearchAiModelsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    503: ErrorResponse;
};

export type SearchAiModelsError = SearchAiModelsErrors[keyof SearchAiModelsErrors];

export type SearchAiModelsResponses = {
    /**
     * Search results mapped to catalog shape
     */
    200: AiModelCatalog;
};

export type SearchAiModelsResponse = SearchAiModelsResponses[keyof SearchAiModelsResponses];

export type ApplyAiModelSelectionData = {
    body: AiApplyRequest;
    path?: never;
    query?: never;
    url: '/ai/runtime/apply';
};

export type ApplyAiModelSelectionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    409: ErrorResponse;
    /**
     * Error response
     */
    503: ErrorResponse;
};

export type ApplyAiModelSelectionError = ApplyAiModelSelectionErrors[keyof ApplyAiModelSelectionErrors];

export type ApplyAiModelSelectionResponses = {
    /**
     * Swap started
     */
    202: AiSwapStatus;
};

export type ApplyAiModelSelectionResponse = ApplyAiModelSelectionResponses[keyof ApplyAiModelSelectionResponses];

export type GetAiApplyStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ai/runtime/apply/status';
};

export type GetAiApplyStatusErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type GetAiApplyStatusError = GetAiApplyStatusErrors[keyof GetAiApplyStatusErrors];

export type GetAiApplyStatusResponses = {
    /**
     * Swap status
     */
    200: AiSwapStatus;
};

export type GetAiApplyStatusResponse = GetAiApplyStatusResponses[keyof GetAiApplyStatusResponses];

export type ListConnectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connections';
};

export type ListConnectionsErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
};

export type ListConnectionsError = ListConnectionsErrors[keyof ListConnectionsErrors];

export type ListConnectionsResponses = {
    /**
     * Linked institutions
     */
    200: ConnectionListResponse;
};

export type ListConnectionsResponse = ListConnectionsResponses[keyof ListConnectionsResponses];

export type CreateConnectionData = {
    body: ConnectionCreateRequest;
    path?: never;
    query?: never;
    url: '/connections';
};

export type CreateConnectionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    422: ErrorResponse;
    /**
     * Error response
     */
    503: ErrorResponse;
};

export type CreateConnectionError = CreateConnectionErrors[keyof CreateConnectionErrors];

export type CreateConnectionResponses = {
    /**
     * Institution linked
     */
    201: InstitutionConnection;
};

export type CreateConnectionResponse = CreateConnectionResponses[keyof CreateConnectionResponses];

export type DeleteConnectionData = {
    body?: never;
    path: {
        connection_id: string;
    };
    query?: never;
    url: '/connections/{connection_id}';
};

export type DeleteConnectionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
};

export type DeleteConnectionError = DeleteConnectionErrors[keyof DeleteConnectionErrors];

export type DeleteConnectionResponses = {
    /**
     * Connection removed
     */
    204: void;
};

export type DeleteConnectionResponse = DeleteConnectionResponses[keyof DeleteConnectionResponses];

export type SyncConnectionData = {
    body?: never;
    path: {
        connection_id: string;
    };
    query?: never;
    url: '/connections/{connection_id}/sync';
};

export type SyncConnectionErrors = {
    /**
     * Error response
     */
    401: ErrorResponse;
    /**
     * Error response
     */
    403: ErrorResponse;
    /**
     * Error response
     */
    404: ErrorResponse;
    /**
     * Error response
     */
    502: ErrorResponse;
};

export type SyncConnectionError = SyncConnectionErrors[keyof SyncConnectionErrors];

export type SyncConnectionResponses = {
    /**
     * Sync result
     */
    200: ConnectionSyncResult;
};

export type SyncConnectionResponse = SyncConnectionResponses[keyof SyncConnectionResponses];
