#!/usr/bin/env bash
#
# Family CFO — one-command full-stack deployment.
#
# Stands up the entire stack with Docker Compose — the Angular dashboard (served
# over HTTPS by nginx), the FastAPI backend, the background worker, PostgreSQL,
# and the local vLLM AI runtime — on a LOCAL or REMOTE Docker host, then prints
# the dashboard URL. For a remote host it prompts for SSH details, syncs the
# repo over SSH, and runs Compose there.
#
# Usage:
#   scripts/deploy.sh                 # interactive (asks local vs remote + SSH)
#   TARGET=local scripts/deploy.sh    # non-interactive local
#   TARGET=remote SSH_HOST=box SSH_USER=me scripts/deploy.sh
#
# Environment overrides (all optional; prompted if unset when needed):
#   TARGET       local | remote
#   SSH_HOST     remote hostname/IP
#   SSH_USER     remote user            (default: current user)
#   SSH_PORT     remote SSH port        (default: 22)
#   SSH_KEY      path to a private key  (default: ssh default resolution)
#   REMOTE_DIR   remote checkout dir    (default: ~/family-cfo)
#   COMPOSE_FILES  compose files        (default: -f docker-compose.yml)
#   NO_BUILD=1   skip image build (use existing images)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

COMPOSE_FILES="${COMPOSE_FILES:--f docker-compose.yml}"
BUILD_FLAG="--build"
[[ "${NO_BUILD:-0}" == "1" ]] && BUILD_FLAG=""

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mError:\033[0m %s\n' "$*" >&2; exit 1; }

# The address other machines on the network use to reach this host — the source
# IP of the default route, falling back to the first `hostname -I` address.
# Published Docker ports bind 0.0.0.0, so the stack is reachable here, not just
# on localhost.
detect_host_ip() {
  local ip
  ip="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')"
  [ -z "$ip" ] && ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  echo "${ip:-localhost}"
}

ask() { # ask VAR "prompt" "default"
  local __var="$1" __prompt="$2" __default="${3:-}" __reply
  if [[ -n "${!__var:-}" ]]; then return; fi
  if [[ -n "$__default" ]]; then
    read -r -p "$__prompt [$__default]: " __reply || true
    printf -v "$__var" '%s' "${__reply:-$__default}"
  else
    read -r -p "$__prompt: " __reply || true
    printf -v "$__var" '%s' "$__reply"
  fi
}

# --- Build a .env if the target doesn't have one -----------------------------
# The stack requires POSTGRES_PASSWORD and (for backups) an encryption key. For
# an easy stand-up we generate strong random values instead of forcing the
# operator to hand-edit before the first boot.
render_env() { # render_env <dest-path>
  local dest="$1"
  local pg_pw enc_key gpu_mb
  pg_pw="$(openssl rand -hex 24 2>/dev/null || head -c 24 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9')"
  enc_key="$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64)"
  # GPU memory for the dashboard's model-fit planner (ADR 0012). Unified-memory
  # hosts (GB10 etc.) report N/A -> left unset; the API falls back to system RAM.
  gpu_mb="$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -dc '0-9')"
  cp .env.example "$dest"
  # Fill required secrets (portable sed: write to temp then move).
  {
    echo ""
    echo "# --- generated by scripts/deploy.sh ---"
    if [ -n "$gpu_mb" ]; then
      echo "FAMILY_CFO_GPU_MEMORY_GB=$(( gpu_mb / 1024 ))"
    fi
    echo "POSTGRES_PASSWORD=${pg_pw}"
    echo "FAMILY_CFO_BACKUP_ENCRYPTION_KEY=${enc_key}"
  } >> "$dest"
  log "Generated a fresh .env with random POSTGRES_PASSWORD and backup key."
}

# AI runs by default and needs a GPU; warn early if the host looks unequipped.
# See the System Requirements table in README.md for per-model RAM/disk.
preflight_ai_advisory() {
  local ai="${FAMILY_CFO_AI_ENABLED:-true}"
  [ "$ai" = "false" ] && return
  if ! command -v nvidia-smi >/dev/null 2>&1; then
    warn "AI is on by default but no nvidia-smi was found — the vllm service needs a GPU + NVIDIA Container Toolkit."
    warn "Run GPU-less with: FAMILY_CFO_AI_ENABLED=false docker compose up -d --scale vllm=0"
  fi
  local free_gb
  free_gb="$(df -Pk . | awk 'NR==2 {print int($4/1024/1024)}')"
  if [ "${free_gb:-0}" -lt 20 ]; then
    warn "Only ${free_gb}GB free here — model weights are tens of GB (see README System Requirements)."
  fi
}

# --- Target selection --------------------------------------------------------
ask TARGET "Deploy target — 'local' or 'remote'" "local"
[[ "$TARGET" == "local" || "$TARGET" == "remote" ]] || die "TARGET must be 'local' or 'remote'."

# =============================================================================
# LOCAL
# =============================================================================
if [[ "$TARGET" == "local" ]]; then
  command -v docker >/dev/null 2>&1 || die "docker is not installed on this host."
  docker compose version >/dev/null 2>&1 || die "docker compose v2 is required."

  if [[ ! -f .env ]]; then
    render_env .env
  else
    log "Using existing .env"
  fi

  preflight_ai_advisory

  log "Building and starting the stack (this pulls the vLLM image + model on first run)…"
  # shellcheck disable=SC2086
  docker compose $COMPOSE_FILES up -d $BUILD_FLAG

  web_tls_port="$(grep -E '^WEB_TLS_PORT=' .env | cut -d= -f2)"; web_tls_port="${web_tls_port:-8443}"
  host_ip="$(detect_host_ip)"
  log "Stack is up."
  echo
  echo "  Dashboard:  https://${host_ip}:${web_tls_port}      (reachable from other machines on the network)"
  echo "              https://localhost:${web_tls_port}     (on this machine)"
  echo "  (self-signed cert — accept the browser warning; see docs/guides/security.md)"
  echo "  Health:     scripts/doctor.sh"
  echo "  Logs:       docker compose $COMPOSE_FILES logs -f"
  echo "  AI status:  docker compose $COMPOSE_FILES logs -f vllm   # first boot downloads the model"
  exit 0
fi

# =============================================================================
# REMOTE
# =============================================================================
command -v rsync >/dev/null 2>&1 || die "rsync is required for remote deploys."
ask SSH_HOST "Remote host (name or IP)"
[[ -n "${SSH_HOST:-}" ]] || die "SSH_HOST is required for a remote deploy."
ask SSH_USER "SSH user" "${USER:-root}"
ask SSH_PORT "SSH port" "22"
ask SSH_KEY  "SSH private key path (blank = ssh default)" ""
ask REMOTE_DIR "Remote directory to deploy into" "~/family-cfo"

SSH_OPTS=(-p "$SSH_PORT" -o StrictHostKeyChecking=accept-new)
[[ -n "${SSH_KEY:-}" ]] && SSH_OPTS+=(-i "$SSH_KEY")
SSH_TARGET="${SSH_USER}@${SSH_HOST}"
# rsync needs the ssh command as one string.
RSH="ssh ${SSH_OPTS[*]}"

remote() { ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "$@"; }

log "Checking SSH connectivity to ${SSH_TARGET}…"
remote true || die "Cannot SSH to ${SSH_TARGET}. Check host/user/port/key."

log "Verifying Docker on the remote host…"
remote 'command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1' \
  || die "Remote host needs Docker Engine + Compose v2 (and the NVIDIA Container Toolkit for the vLLM/AI service)."

# Expand a leading ~ on the remote side and ensure the dir exists.
REMOTE_ABS="$(remote "mkdir -p ${REMOTE_DIR} && cd ${REMOTE_DIR} && pwd")"
log "Deploying into ${SSH_TARGET}:${REMOTE_ABS}"

log "Syncing project files (excluding build artifacts and local data)…"
rsync -az --delete \
  --exclude '.git' --exclude 'node_modules' --exclude '.venv' \
  --exclude '__pycache__' --exclude 'dist' --exclude '.angular' \
  --exclude 'data' --exclude '*.db' \
  --exclude '.env' \
  -e "$RSH" \
  "$REPO_ROOT/" "${SSH_TARGET}:${REMOTE_ABS}/"

# Ensure the remote has a .env (kept out of rsync so we never clobber remote
# secrets); generate one from the example on first deploy.
if remote "test -f ${REMOTE_ABS}/.env"; then
  log "Remote already has a .env — leaving its secrets untouched."
else
  log "No remote .env — generating one with random secrets…"
  tmp_env="$(mktemp)"
  render_env "$tmp_env"
  rsync -az -e "$RSH" "$tmp_env" "${SSH_TARGET}:${REMOTE_ABS}/.env"
  rm -f "$tmp_env"
fi

log "Building and starting the stack on the remote host…"
remote "cd ${REMOTE_ABS} && docker compose ${COMPOSE_FILES} up -d ${BUILD_FLAG}"

web_tls_port="$(remote "grep -E '^WEB_TLS_PORT=' ${REMOTE_ABS}/.env | cut -d= -f2" || true)"
web_tls_port="${web_tls_port:-8443}"

log "Deployed."
echo
echo "  Dashboard:  https://${SSH_HOST}:${web_tls_port}"
echo "  (self-signed cert — accept the browser warning; see docs/guides/security.md)"
echo "  Health:     ssh ${SSH_TARGET} 'cd ${REMOTE_ABS} && bash scripts/doctor.sh'"
echo "  Logs:       ssh ${SSH_TARGET} 'cd ${REMOTE_ABS} && docker compose ${COMPOSE_FILES} logs -f'"
echo "  AI status:  ssh ${SSH_TARGET} 'cd ${REMOTE_ABS} && docker compose ${COMPOSE_FILES} logs -f vllm'"
echo
warn "First boot downloads the vLLM model (multi-GB) — the AI advisor is ready once 'vllm' finishes loading."
